// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pyrconstuct_top_Loop_3_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgOutTmpBlockRam_M_real_V_address0,
        imgOutTmpBlockRam_M_real_V_ce0,
        imgOutTmpBlockRam_M_real_V_q0,
        imgOutTmpBlockRam_M_imag_V_address0,
        imgOutTmpBlockRam_M_imag_V_ce0,
        imgOutTmpBlockRam_M_imag_V_q0,
        fftPyrOut_M_real_V_din,
        fftPyrOut_M_real_V_full_n,
        fftPyrOut_M_real_V_write,
        fftPyrOut_M_imag_V_din,
        fftPyrOut_M_imag_V_full_n,
        fftPyrOut_M_imag_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st8_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv11_5F0 = 11'b10111110000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_200 = 32'b1000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [8:0] imgOutTmpBlockRam_M_real_V_address0;
output   imgOutTmpBlockRam_M_real_V_ce0;
input  [23:0] imgOutTmpBlockRam_M_real_V_q0;
output  [8:0] imgOutTmpBlockRam_M_imag_V_address0;
output   imgOutTmpBlockRam_M_imag_V_ce0;
input  [23:0] imgOutTmpBlockRam_M_imag_V_q0;
output  [23:0] fftPyrOut_M_real_V_din;
input   fftPyrOut_M_real_V_full_n;
output   fftPyrOut_M_real_V_write;
output  [23:0] fftPyrOut_M_imag_V_din;
input   fftPyrOut_M_imag_V_full_n;
output   fftPyrOut_M_imag_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgOutTmpBlockRam_M_real_V_ce0;
reg imgOutTmpBlockRam_M_imag_V_ce0;
reg fftPyrOut_M_real_V_write;
reg fftPyrOut_M_imag_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
wire   [3:0] limits_address0;
reg    limits_ce0;
wire   [9:0] limits_q0;
wire   [10:0] consFilters_V_address0;
reg    consFilters_V_ce0;
wire   [8:0] consFilters_V_q0;
reg   [10:0] l_0_i_reg_120;
reg   [31:0] idx_reg_132;
reg   [10:0] coefIdx_0_i_reg_144;
wire   [0:0] exitcond_i2_fu_155_p2;
reg   [0:0] exitcond_i2_reg_297;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_76;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4;
reg    ap_sig_bdd_96;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_i2_reg_297_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_i2_reg_297_pp0_it3;
wire   [10:0] coefIdx_fu_161_p2;
wire   [31:0] idx_2_fu_213_p3;
reg   [31:0] idx_2_reg_316;
reg   [8:0] consFilters_V_load_reg_321;
reg   [8:0] ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it2;
reg   [8:0] ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it3;
wire   [10:0] l_fu_237_p2;
wire   [31:0] i_1_fu_243_p3;
reg   [31:0] i_1_reg_331;
reg  signed [23:0] imgOutTmpBlockRam_M_real_V_lo_reg_346;
reg  signed [23:0] imgOutTmpBlockRam_M_imag_V_lo_reg_351;
reg   [23:0] tmp_9_reg_356;
reg   [23:0] tmp_s_reg_361;
reg    ap_sig_bdd_150;
reg   [10:0] l_0_i_phi_fu_124_p4;
reg   [31:0] idx_phi_fu_136_p4;
wire   [63:0] tmp_3_fu_167_p1;
wire   [63:0] tmp_8_fu_172_p1;
wire  signed [63:0] tmp_7_fu_251_p1;
wire   [8:0] tmp_4_fu_181_p4;
wire   [31:0] half_fu_191_p1;
wire   [31:0] tmp_5_fu_201_p2;
wire   [31:0] nlimit_cast_fu_177_p1;
wire   [0:0] tmp_6_fu_195_p2;
wire   [31:0] idx_1_fu_207_p2;
wire   [31:0] i_fu_221_p2;
wire   [0:0] tmp_1_fu_227_p2;
wire   [10:0] tmp_18_cast_fu_233_p1;
wire  signed [31:0] p_Val2_s_fu_290_p2;
wire  signed [31:0] p_Val2_1_fu_283_p2;
wire   [8:0] p_Val2_1_fu_283_p0;
wire   [31:0] OP2_V_cast_fu_262_p1;
wire   [8:0] p_Val2_s_fu_290_p0;
reg    ap_sig_cseq_ST_st8_fsm_2;
reg    ap_sig_bdd_267;
reg   [2:0] ap_NS_fsm;


pyrconstuct_top_Loop_3_proc_limits #(
    .DataWidth( 10 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
limits_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( limits_address0 ),
    .ce0( limits_ce0 ),
    .q0( limits_q0 )
);

pyrconstuct_top_Loop_3_proc_consFilters_V #(
    .DataWidth( 9 ),
    .AddressRange( 1520 ),
    .AddressWidth( 11 ))
consFilters_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( consFilters_V_address0 ),
    .ce0( consFilters_V_ce0 ),
    .q0( consFilters_V_q0 )
);

pyrconstuct_top_mul_mul_9ns_24s_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
pyrconstuct_top_mul_mul_9ns_24s_32_1_U8(
    .din0( p_Val2_1_fu_283_p0 ),
    .din1( imgOutTmpBlockRam_M_imag_V_lo_reg_351 ),
    .dout( p_Val2_1_fu_283_p2 )
);

pyrconstuct_top_mul_mul_9ns_24s_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
pyrconstuct_top_mul_mul_9ns_24s_32_1_U9(
    .din0( p_Val2_s_fu_290_p0 ),
    .din1( imgOutTmpBlockRam_M_real_V_lo_reg_346 ),
    .dout( p_Val2_s_fu_290_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(exitcond_i2_fu_155_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (exitcond_i2_fu_155_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(exitcond_i2_fu_155_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150)) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150)) begin
        coefIdx_0_i_reg_144 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (exitcond_i2_fu_155_p2 == ap_const_lv1_0))) begin
        coefIdx_0_i_reg_144 <= coefIdx_fu_161_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150)) begin
        idx_reg_132 <= ap_const_lv32_0;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1))) begin
        idx_reg_132 <= i_1_reg_331;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_150)) begin
        l_0_i_reg_120 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (exitcond_i2_reg_297 == ap_const_lv1_0))) begin
        l_0_i_reg_120 <= l_fu_237_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) begin
        ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it2 <= consFilters_V_load_reg_321;
        ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it3 <= ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it2;
        ap_reg_ppstg_exitcond_i2_reg_297_pp0_it2 <= ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1;
        ap_reg_ppstg_exitcond_i2_reg_297_pp0_it3 <= ap_reg_ppstg_exitcond_i2_reg_297_pp0_it2;
        ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 <= ap_reg_ppstg_exitcond_i2_reg_297_pp0_it3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1 <= exitcond_i2_reg_297;
        exitcond_i2_reg_297 <= exitcond_i2_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (exitcond_i2_reg_297 == ap_const_lv1_0))) begin
        consFilters_V_load_reg_321 <= consFilters_V_q0;
        idx_2_reg_316 <= idx_2_fu_213_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (exitcond_i2_reg_297 == ap_const_lv1_0))) begin
        i_1_reg_331 <= i_1_fu_243_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i2_reg_297_pp0_it2))) begin
        imgOutTmpBlockRam_M_imag_V_lo_reg_351 <= imgOutTmpBlockRam_M_imag_V_q0;
        imgOutTmpBlockRam_M_real_V_lo_reg_346 <= imgOutTmpBlockRam_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i2_reg_297_pp0_it3))) begin
        tmp_9_reg_356 <= {{p_Val2_s_fu_290_p2[ap_const_lv32_1F : ap_const_lv32_8]}};
        tmp_s_reg_361 <= {{p_Val2_1_fu_283_p2[ap_const_lv32_1F : ap_const_lv32_8]}};
    end
end

always @ (ap_done_reg or ap_sig_cseq_ST_st8_fsm_2) begin
    if (((ap_const_logic_1 == ap_done_reg) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st8_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_76) begin
    if (ap_sig_bdd_76) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_267) begin
    if (ap_sig_bdd_267) begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        consFilters_V_ce0 = ap_const_logic_1;
    end else begin
        consFilters_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        fftPyrOut_M_imag_V_write = ap_const_logic_1;
    end else begin
        fftPyrOut_M_imag_V_write = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        fftPyrOut_M_real_V_write = ap_const_logic_1;
    end else begin
        fftPyrOut_M_real_V_write = ap_const_logic_0;
    end
end

always @ (idx_reg_132 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1 or i_1_reg_331) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i2_reg_297_pp0_it1))) begin
        idx_phi_fu_136_p4 = i_1_reg_331;
    end else begin
        idx_phi_fu_136_p4 = idx_reg_132;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        imgOutTmpBlockRam_M_imag_V_ce0 = ap_const_logic_1;
    end else begin
        imgOutTmpBlockRam_M_imag_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        imgOutTmpBlockRam_M_real_V_ce0 = ap_const_logic_1;
    end else begin
        imgOutTmpBlockRam_M_real_V_ce0 = ap_const_logic_0;
    end
end

always @ (l_0_i_reg_120 or exitcond_i2_reg_297 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or l_fu_237_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_i2_reg_297 == ap_const_lv1_0))) begin
        l_0_i_phi_fu_124_p4 = l_fu_237_p2;
    end else begin
        l_0_i_phi_fu_124_p4 = l_0_i_reg_120;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        limits_ce0 = ap_const_logic_1;
    end else begin
        limits_ce0 = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or exitcond_i2_fu_155_p2 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_150) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_150) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(exitcond_i2_fu_155_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~(exitcond_i2_fu_155_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st8_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st8_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign OP2_V_cast_fu_262_p1 = ap_reg_ppstg_consFilters_V_load_reg_321_pp0_it3;


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_150 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_267 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_76 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (fftPyrOut_M_real_V_full_n or fftPyrOut_M_imag_V_full_n or ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4) begin
    ap_sig_bdd_96 = (((fftPyrOut_M_real_V_full_n == ap_const_logic_0) & (ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 == ap_const_lv1_0)) | ((ap_reg_ppstg_exitcond_i2_reg_297_pp0_it4 == ap_const_lv1_0) & (fftPyrOut_M_imag_V_full_n == ap_const_logic_0)));
end

assign coefIdx_fu_161_p2 = (coefIdx_0_i_reg_144 + ap_const_lv11_1);

assign consFilters_V_address0 = tmp_8_fu_172_p1;

assign exitcond_i2_fu_155_p2 = (coefIdx_0_i_reg_144 == ap_const_lv11_5F0? 1'b1: 1'b0);

assign fftPyrOut_M_imag_V_din = tmp_s_reg_361;

assign fftPyrOut_M_real_V_din = tmp_9_reg_356;

assign half_fu_191_p1 = tmp_4_fu_181_p4;

assign i_1_fu_243_p3 = ((tmp_1_fu_227_p2[0:0] === 1'b1) ? ap_const_lv32_0 : i_fu_221_p2);

assign i_fu_221_p2 = (idx_phi_fu_136_p4 + ap_const_lv32_1);

assign idx_1_fu_207_p2 = (tmp_5_fu_201_p2 - nlimit_cast_fu_177_p1);

assign idx_2_fu_213_p3 = ((tmp_6_fu_195_p2[0:0] === 1'b1) ? idx_phi_fu_136_p4 : idx_1_fu_207_p2);

assign imgOutTmpBlockRam_M_imag_V_address0 = tmp_7_fu_251_p1;

assign imgOutTmpBlockRam_M_real_V_address0 = tmp_7_fu_251_p1;

assign l_fu_237_p2 = (l_0_i_reg_120 + tmp_18_cast_fu_233_p1);

assign limits_address0 = tmp_3_fu_167_p1;

assign nlimit_cast_fu_177_p1 = limits_q0;

assign p_Val2_1_fu_283_p0 = OP2_V_cast_fu_262_p1;

assign p_Val2_s_fu_290_p0 = OP2_V_cast_fu_262_p1;

assign tmp_18_cast_fu_233_p1 = tmp_1_fu_227_p2;

assign tmp_1_fu_227_p2 = (nlimit_cast_fu_177_p1 == i_fu_221_p2? 1'b1: 1'b0);

assign tmp_3_fu_167_p1 = l_0_i_phi_fu_124_p4;

assign tmp_4_fu_181_p4 = {{limits_q0[ap_const_lv32_9 : ap_const_lv32_1]}};

assign tmp_5_fu_201_p2 = (idx_phi_fu_136_p4 + ap_const_lv32_200);

assign tmp_6_fu_195_p2 = ($signed(idx_phi_fu_136_p4) < $signed(half_fu_191_p1)? 1'b1: 1'b0);

assign tmp_7_fu_251_p1 = $signed(idx_2_reg_316);

assign tmp_8_fu_172_p1 = coefIdx_0_i_reg_144;


endmodule //pyrconstuct_top_Loop_3_proc

