// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      cmpy_complex_top
`define AUTOTB_DUT_INST AESL_inst_cmpy_complex_top
`define AUTOTB_TOP      apatb_cmpy_complex_top_top
`define AUTOTB_LAT_RESULT_FILE "cmpy_complex_top.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "cmpy_complex_top.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_cmpy_complex_top_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_TRANSACTION_NUM  1
`define AUTOTB_CLOCK_PERIOD_DIV2 5.00
`define LENGTH_sig 1024
`define LENGTH_sigRef 2048
`define LENGTH_prealign_V 1024
`define LENGTH_cmp 1024
`define LENGTH_nL 1
`define LENGTH_factor_V 1

`define   AESL_DEPTH_sig 1
`define   AESL_DEPTH_sigRef 1
`define   AESL_DEPTH_prealign_V 1
`define   AESL_DEPTH_cmp 1
`define   AESL_DEPTH_nL 1
`define   AESL_DEPTH_nLExp 1
`define   AESL_DEPTH_nLen 1
`define   AESL_DEPTH_factor_V 1
`define AUTOTB_TVIN_sig  "./c.cmpy_complex_top.autotvin_sig.dat"
`define AUTOTB_TVIN_sigRef  "./c.cmpy_complex_top.autotvin_sigRef.dat"
`define AUTOTB_TVIN_prealign_V  "./c.cmpy_complex_top.autotvin_prealign_V.dat"
`define AUTOTB_TVIN_cmp  "./c.cmpy_complex_top.autotvin_cmp.dat"
`define AUTOTB_TVIN_nL  "./c.cmpy_complex_top.autotvin_nL.dat"
`define AUTOTB_TVIN_factor_V  "./c.cmpy_complex_top.autotvin_factor_V.dat"
`define AUTOTB_TVIN_sig_out_wrapc  "./rtl.cmpy_complex_top.autotvin_sig.dat"
`define AUTOTB_TVIN_sigRef_out_wrapc  "./rtl.cmpy_complex_top.autotvin_sigRef.dat"
`define AUTOTB_TVIN_prealign_V_out_wrapc  "./rtl.cmpy_complex_top.autotvin_prealign_V.dat"
`define AUTOTB_TVIN_cmp_out_wrapc  "./rtl.cmpy_complex_top.autotvin_cmp.dat"
`define AUTOTB_TVIN_nL_out_wrapc  "./rtl.cmpy_complex_top.autotvin_nL.dat"
`define AUTOTB_TVIN_factor_V_out_wrapc  "./rtl.cmpy_complex_top.autotvin_factor_V.dat"
`define AUTOTB_TVOUT_cmp  "./c.cmpy_complex_top.autotvout_cmp.dat"
`define AUTOTB_TVOUT_cmp_out_wrapc  "./impl_rtl.cmpy_complex_top.autotvout_cmp.dat"

module `AUTOTB_TOP;

task read_token;
    input integer fp;
    output reg [159 : 0] token;
    reg [7:0] c;
    reg intoken;
    reg done;
    begin
        token = "";
        intoken = 0;
        done = 0;
        while (!done) begin
            c = $fgetc(fp);
            if (c == 8'hff) begin   // EOF
                done = 1;
            end
            else if (c == " " || c == "\011" || c == "\012" || c == "\015") begin   // blank
                if (intoken) begin
                    done = 1;
                end
            end
            else begin              // valid character
                intoken = 1;
                token = (token << 8) | c;
            end
        end
    end
endtask

task post_check;
    input integer fp1;
    input integer fp2;
    reg [159 : 0] token1;
    reg [159 : 0] token2;
    reg [159 : 0] golden;
    reg [159 : 0] result;
    integer ret;
    begin
        read_token(fp1, token1);
        read_token(fp2, token2);
        if (token1 != "[[[runtime]]]" || token2 != "[[[runtime]]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
            $finish;
        end
        read_token(fp1, token1);
        read_token(fp2, token2);
        while (token1 != "[[[/runtime]]]" && token2 != "[[[/runtime]]]") begin
            if (token1 != "[[transaction]]" || token2 != "[[transaction]]") begin
                $display("ERROR: Simulation using HLS TB failed.");
	              $finish;
            end
            read_token(fp1, token1);  // skip transaction number
            read_token(fp2, token2);  // skip transaction number
	          read_token(fp1, token1);
	          read_token(fp2, token2);
            while(token1 != "[[/transaction]]" && token2 != "[[/transaction]]") begin
                ret = $sscanf(token1, "0x%x", golden);
	              if (ret != 1) begin
	                  $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
	                  $finish;
	              end
                ret = $sscanf(token2, "0x%x", result);
	              if (ret != 1) begin
	                  $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
	                  $finish;
	              end
                if(golden != result) begin
	                  $display("%x (expected) vs. %x (actual) - mismatch", golden, result);
                    $display("ERROR: Simulation using HLS TB failed.");
	                  $finish;
                end
	              read_token(fp1, token1);
	              read_token(fp2, token2);
            end
	          read_token(fp1, token1);
	          read_token(fp2, token2);
        end
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
reg [31 : 0] AESL_mLatCnterIn [0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [31 : 0] AESL_mLatCnterIn_addr;
reg [31 : 0] AESL_mLatCnterOut [0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [31 : 0] AESL_mLatCnterOut_addr ;
reg [31 : 0] AESL_clk_counter ;
reg [ - 1 : 0] AESL_clk_ready[0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [ - 1 : 0] AESL_clk_done[0 : `AUTOTB_TRANSACTION_NUM + 1];

reg reported_stuck = 0;
reg reported_stuck_cnt = 0;
wire [23 : 0] sig_TDATA;
wire [23 : 0] sigRef_TDATA;
wire [23 : 0] prealign_V_TDATA;
wire [39 : 0] cmp_TDATA;
wire [31 : 0] nL;
wire [31 : 0] nLExp;
wire [31 : 0] nLen;
wire [9 : 0] factor_V;
wire  sigRef_TVALID;
wire  sigRef_TREADY;
wire  prealign_V_TVALID;
wire  prealign_V_TREADY;
wire  sig_TVALID;
wire  sig_TREADY;
wire  cmp_TVALID;
wire  cmp_TREADY;
wire ap_done;
wire ap_start;
wire ap_idle;
wire ap_ready;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;

`AUTOTB_DUT `AUTOTB_DUT_INST(
	.ap_clk(ap_clk),
	.ap_rst_n(ap_rst_n),
	.sig_TDATA(sig_TDATA),
	.sigRef_TDATA(sigRef_TDATA),
	.prealign_V_TDATA(prealign_V_TDATA),
	.cmp_TDATA(cmp_TDATA),
	.nL(nL),
	.nLExp(nLExp),
	.nLen(nLen),
	.factor_V(factor_V),
	.sigRef_TVALID(sigRef_TVALID),
	.sigRef_TREADY(sigRef_TREADY),
	.prealign_V_TVALID(prealign_V_TVALID),
	.prealign_V_TREADY(prealign_V_TREADY),
	.sig_TVALID(sig_TVALID),
	.sig_TREADY(sig_TREADY),
	.cmp_TVALID(cmp_TVALID),
	.cmp_TREADY(cmp_TREADY),
	.ap_done(ap_done),
	.ap_start(ap_start),
	.ap_idle(ap_idle),
	.ap_ready(ap_ready));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst_n = AESL_reset;
assign ap_rst_n_n = ~AESL_reset;
assign AESL_reset = rst;
assign AESL_done = ap_done;
assign ap_start = AESL_start;
assign AESL_start = start;
assign AESL_idle = ap_idle;
assign AESL_ready = ap_ready;
assign AESL_ce = ce;
assign AESL_continue = continue;
	always @(posedge AESL_clock) begin
		if (AESL_reset === 0) begin
		end else begin
			if (AESL_done !== 1 && AESL_done !== 0) begin
				$display("ERROR: Control signal AESL_done is invalid!");
				$finish;
			end
		end
	end
	always @(posedge AESL_clock) begin
		if (AESL_reset === 0) begin
		end else begin
			if (AESL_ready !== 1 && AESL_ready !== 0) begin
				$display("ERROR: Control signal AESL_ready is invalid!");
				$finish;
			end
		end
	end




// The signal of port nL
reg [31: 0] AESL_REG_nL = 0;
assign nL = AESL_REG_nL;
initial begin : read_file_process_nL
    integer fp;
    integer err;
    integer ret;
    integer rand;
    reg [159  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 1);
    fp = $fopen(`AUTOTB_TVIN_nL,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_nL);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
	          $finish;
        end
        read_token(fp, token);  // skip transaction number
	      read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_nL);
	          if (ret != 1) begin
	              $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
	              $finish;
	          end
            @(posedge AESL_clock);
	          read_token(fp, token);
        end
	      read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port nLExp
reg [31: 0] AESL_REG_nLExp = 0;
assign nLExp = AESL_REG_nLExp;

// The signal of port nLen
reg [31: 0] AESL_REG_nLen = 0;
assign nLen = AESL_REG_nLen;

// The signal of port factor_V
reg [9: 0] AESL_REG_factor_V = 0;
assign factor_V = AESL_REG_factor_V;
initial begin : read_file_process_factor_V
    integer fp;
    integer err;
    integer ret;
    integer rand;
    reg [159  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 1);
    fp = $fopen(`AUTOTB_TVIN_factor_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_factor_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
	          $finish;
        end
        read_token(fp, token);  // skip transaction number
	      read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_factor_V);
	          if (ret != 1) begin
	              $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
	              $finish;
	          end
            @(posedge AESL_clock);
	          read_token(fp, token);
        end
	      read_token(fp, token);
    end
    $fclose(fp);
end


reg [31:0] ap_c_n_tvin_trans_num_sig;
reg sig_ready_reg; // for self-sync

wire sig_ready;
wire sig_done;
wire [31:0] sig_transaction;
wire axi_s_sig_TVALID;
wire axi_s_sig_TREADY;

AESL_axi_s_sig AESL_AXI_S_sig(
	.clk(AESL_clock),
	.reset(AESL_reset),
	.TRAN_sig_TDATA(sig_TDATA),
	.TRAN_sig_TVALID(axi_s_sig_TVALID),
	.TRAN_sig_TREADY(axi_s_sig_TREADY),
	.ready(sig_ready),
	.done(sig_done),
	.transaction(sig_transaction));

assign sig_ready = ready;
assign sig_done = 0;

reg reg_sig_TVALID;
initial begin : gen_reg_sig_TVALID_process
	integer rand;
	reg_sig_TVALID = axi_s_sig_TVALID;
	while (1) begin
		@ (axi_s_sig_TVALID);
		reg_sig_TVALID = axi_s_sig_TVALID;
	end
end


assign sig_TVALID = reg_sig_TVALID;

assign axi_s_sig_TREADY = sig_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_sigRef;
reg sigRef_ready_reg; // for self-sync

wire sigRef_ready;
wire sigRef_done;
wire [31:0] sigRef_transaction;
wire axi_s_sigRef_TVALID;
wire axi_s_sigRef_TREADY;

AESL_axi_s_sigRef AESL_AXI_S_sigRef(
	.clk(AESL_clock),
	.reset(AESL_reset),
	.TRAN_sigRef_TDATA(sigRef_TDATA),
	.TRAN_sigRef_TVALID(axi_s_sigRef_TVALID),
	.TRAN_sigRef_TREADY(axi_s_sigRef_TREADY),
	.ready(sigRef_ready),
	.done(sigRef_done),
	.transaction(sigRef_transaction));

assign sigRef_ready = ready;
assign sigRef_done = 0;

reg reg_sigRef_TVALID;
initial begin : gen_reg_sigRef_TVALID_process
	integer rand;
	reg_sigRef_TVALID = axi_s_sigRef_TVALID;
	while (1) begin
		@ (axi_s_sigRef_TVALID);
		reg_sigRef_TVALID = axi_s_sigRef_TVALID;
	end
end


assign sigRef_TVALID = reg_sigRef_TVALID;

assign axi_s_sigRef_TREADY = sigRef_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_prealign_V;
reg prealign_V_ready_reg; // for self-sync

wire prealign_V_ready;
wire prealign_V_done;
wire [31:0] prealign_V_transaction;
wire axi_s_prealign_V_TVALID;
wire axi_s_prealign_V_TREADY;

AESL_axi_s_prealign_V AESL_AXI_S_prealign_V(
	.clk(AESL_clock),
	.reset(AESL_reset),
	.TRAN_prealign_V_TDATA(prealign_V_TDATA),
	.TRAN_prealign_V_TVALID(axi_s_prealign_V_TVALID),
	.TRAN_prealign_V_TREADY(axi_s_prealign_V_TREADY),
	.ready(prealign_V_ready),
	.done(prealign_V_done),
	.transaction(prealign_V_transaction));

assign prealign_V_ready = ready;
assign prealign_V_done = 0;

reg reg_prealign_V_TVALID;
initial begin : gen_reg_prealign_V_TVALID_process
	integer rand;
	reg_prealign_V_TVALID = axi_s_prealign_V_TVALID;
	while (1) begin
		@ (axi_s_prealign_V_TVALID);
		reg_prealign_V_TVALID = axi_s_prealign_V_TVALID;
	end
end


assign prealign_V_TVALID = reg_prealign_V_TVALID;

assign axi_s_prealign_V_TREADY = prealign_V_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_cmp;
reg cmp_ready_reg; // for self-sync

wire cmp_ready;
wire cmp_done;
wire [31:0] cmp_transaction;
wire axi_s_cmp_TVALID;
wire axi_s_cmp_TREADY;

AESL_axi_s_cmp AESL_AXI_S_cmp(
	.clk(AESL_clock),
	.reset(AESL_reset),
	.TRAN_cmp_TDATA(cmp_TDATA),
	.TRAN_cmp_TVALID(axi_s_cmp_TVALID),
	.TRAN_cmp_TREADY(axi_s_cmp_TREADY),
	.ready(cmp_ready),
	.done(cmp_done),
	.transaction(cmp_transaction));

assign cmp_ready = 0;
assign cmp_done = AESL_done;

assign axi_s_cmp_TVALID = cmp_TVALID;

reg reg_cmp_TREADY;
initial begin : gen_reg_cmp_TREADY_process
    integer rand;
    reg_cmp_TREADY = 0;
    while(1)
    begin
        @(axi_s_cmp_TREADY);
        reg_cmp_TREADY = axi_s_cmp_TREADY;
    end
end


assign cmp_TREADY = reg_cmp_TREADY;

initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 1);
    while(AESL_ready_cnt != `AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

	event next_trigger_ready_cnt;
	
	initial begin : gen_ready_cnt
		ready_cnt = 0;
		wait (AESL_reset === 1);
		forever begin
			@ (posedge AESL_clock);
			if (ready == 1) begin
				if (ready_cnt < `AUTOTB_TRANSACTION_NUM) begin
					ready_cnt = ready_cnt + 1;
				end
			end
			-> next_trigger_ready_cnt;
		end
	end
	
	wire all_finish = (done_cnt == `AUTOTB_TRANSACTION_NUM);
	
	// done_cnt
	always @ (posedge AESL_clock) begin
		if (~AESL_reset) begin
			done_cnt <= 0;
		end else begin
			if (AESL_done == 1) begin
				if (done_cnt < `AUTOTB_TRANSACTION_NUM) begin
					done_cnt <= done_cnt + 1;
				end
			end
		end
	end
	
	initial begin : finish_simulation
		integer fp1;
		integer fp2;
		wait (all_finish == 1);
		// last transaction is saved at negedge right after last done
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
    fp1 = $fopen("./rtl.cmpy_complex_top.autotvout_cmp.dat", "r");
    fp2 = $fopen("./impl_rtl.cmpy_complex_top.autotvout_cmp.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.cmpy_complex_top.autotvout_cmp.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.cmpy_complex_top.autotvout_cmp.dat\"!");
    else begin
        $display("Comparing rtl.cmpy_complex_top.autotvout_cmp.dat with impl_rtl.cmpy_complex_top.autotvout_cmp.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
		$display("Simulation Passed.");
		$finish;
	end
	
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_sig;
reg [31:0] size_sig;
reg end_sigRef;
reg [31:0] size_sigRef;
reg end_prealign_V;
reg [31:0] size_prealign_V;
reg end_cmp;
reg [31:0] size_cmp;
reg end_nL;
reg [31:0] size_nL;
reg end_factor_V;
reg [31:0] size_factor_V;

initial begin : initial_process
    integer rand;
    rst = 0;
    # 100;
	  repeat(3) @(posedge AESL_clock);
    rst = 1;
end

initial begin : start_process
	integer rand;
	start = 0;
	ce = 1;
	wait (AESL_reset === 1);
	@ (posedge AESL_clock);
	start = 1;
	while (ready_cnt < `AUTOTB_TRANSACTION_NUM + 1) begin
		@ (posedge AESL_clock);
	end
	start = 0;
end

always @(AESL_done)
begin
    continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == `AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < `AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < `AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == `AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end
	
	initial begin : proc_gen_axis_internal_ready_sig
		sig_ready_reg = 0;
		@ (posedge ready_initial);
		forever begin
			@ (ap_c_n_tvin_trans_num_sig or sig_transaction);
			if (ap_c_n_tvin_trans_num_sig > sig_transaction) begin
				sig_ready_reg = 1;
			end else begin
				sig_ready_reg = 0;
			end
		end
	end
	
	initial begin : proc_gen_axis_internal_ready_sigRef
		sigRef_ready_reg = 0;
		@ (posedge ready_initial);
		forever begin
			@ (ap_c_n_tvin_trans_num_sigRef or sigRef_transaction);
			if (ap_c_n_tvin_trans_num_sigRef > sigRef_transaction) begin
				sigRef_ready_reg = 1;
			end else begin
				sigRef_ready_reg = 0;
			end
		end
	end
	
	initial begin : proc_gen_axis_internal_ready_prealign_V
		prealign_V_ready_reg = 0;
		@ (posedge ready_initial);
		forever begin
			@ (ap_c_n_tvin_trans_num_prealign_V or prealign_V_transaction);
			if (ap_c_n_tvin_trans_num_prealign_V > prealign_V_transaction) begin
				prealign_V_ready_reg = 1;
			end else begin
				prealign_V_ready_reg = 0;
			end
		end
	end
	`define STREAM_SIZE_IN_sig "./stream_size_in_sig.dat"
	
	initial begin : gen_ap_c_n_tvin_trans_num_sig
		integer fp_sig;
		reg [127:0] token_sig;
		integer ret;
		
		ap_c_n_tvin_trans_num_sig = 0;
		end_sig = 0;
		wait (AESL_reset === 1);
		
		fp_sig = $fopen(`AUTOTB_TVIN_sig, "r");
		if(fp_sig == 0) begin
			$display("Failed to open file \"%s\"!", `AUTOTB_TVIN_sig);
			$finish;
		end
		read_token(fp_sig, token_sig); // should be [[[runtime]]]
		if (token_sig != "[[[runtime]]]") begin
			$display("ERROR: token_sig != \"[[[runtime]]]\"");
			$finish;
		end
		ap_c_n_tvin_trans_num_sig = ap_c_n_tvin_trans_num_sig + 1;
		read_token(fp_sig, token_sig); // should be [[transaction]] or [[[/runtime]]]
		if (token_sig == "[[[/runtime]]]") begin
			$fclose(fp_sig);
			end_sig = 1;
		end else begin
			end_sig = 0;
			read_token(fp_sig, token_sig); // should be transaction number
			read_token(fp_sig, token_sig);
		end
		while (token_sig == "[[/transaction]]" && end_sig == 0) begin
			ap_c_n_tvin_trans_num_sig = ap_c_n_tvin_trans_num_sig + 1;
			read_token(fp_sig, token_sig); // should be [[transaction]] or [[[/runtime]]]
			if (token_sig == "[[[/runtime]]]") begin
				$fclose(fp_sig);
				end_sig = 1;
			end else begin
				end_sig = 0;
				read_token(fp_sig, token_sig); // should be transaction number
				read_token(fp_sig, token_sig);
			end
		end
		forever begin
			@ (posedge AESL_clock);
			if (end_sig == 0) begin
				if (sig_TREADY == 1) begin
					read_token(fp_sig, token_sig);
					while (token_sig == "[[/transaction]]" && end_sig == 0) begin
						ap_c_n_tvin_trans_num_sig = ap_c_n_tvin_trans_num_sig + 1;
						read_token(fp_sig, token_sig); // should be [[transaction]] or [[[/runtime]]]
						if (token_sig == "[[[/runtime]]]") begin
							$fclose(fp_sig);
							end_sig = 1;
						end else begin
							end_sig = 0;
							read_token(fp_sig, token_sig); // should be transaction number
							read_token(fp_sig, token_sig);
						end
					end
				end
			end else begin
				ap_c_n_tvin_trans_num_sig = ap_c_n_tvin_trans_num_sig + 1;
			end
		end
	end
	
	`define STREAM_SIZE_IN_sigRef "./stream_size_in_sigRef.dat"
	
	initial begin : gen_ap_c_n_tvin_trans_num_sigRef
		integer fp_sigRef;
		reg [127:0] token_sigRef;
		integer ret;
		
		ap_c_n_tvin_trans_num_sigRef = 0;
		end_sigRef = 0;
		wait (AESL_reset === 1);
		
		fp_sigRef = $fopen(`AUTOTB_TVIN_sigRef, "r");
		if(fp_sigRef == 0) begin
			$display("Failed to open file \"%s\"!", `AUTOTB_TVIN_sigRef);
			$finish;
		end
		read_token(fp_sigRef, token_sigRef); // should be [[[runtime]]]
		if (token_sigRef != "[[[runtime]]]") begin
			$display("ERROR: token_sigRef != \"[[[runtime]]]\"");
			$finish;
		end
		ap_c_n_tvin_trans_num_sigRef = ap_c_n_tvin_trans_num_sigRef + 1;
		read_token(fp_sigRef, token_sigRef); // should be [[transaction]] or [[[/runtime]]]
		if (token_sigRef == "[[[/runtime]]]") begin
			$fclose(fp_sigRef);
			end_sigRef = 1;
		end else begin
			end_sigRef = 0;
			read_token(fp_sigRef, token_sigRef); // should be transaction number
			read_token(fp_sigRef, token_sigRef);
		end
		while (token_sigRef == "[[/transaction]]" && end_sigRef == 0) begin
			ap_c_n_tvin_trans_num_sigRef = ap_c_n_tvin_trans_num_sigRef + 1;
			read_token(fp_sigRef, token_sigRef); // should be [[transaction]] or [[[/runtime]]]
			if (token_sigRef == "[[[/runtime]]]") begin
				$fclose(fp_sigRef);
				end_sigRef = 1;
			end else begin
				end_sigRef = 0;
				read_token(fp_sigRef, token_sigRef); // should be transaction number
				read_token(fp_sigRef, token_sigRef);
			end
		end
		forever begin
			@ (posedge AESL_clock);
			if (end_sigRef == 0) begin
				if (sigRef_TREADY == 1) begin
					read_token(fp_sigRef, token_sigRef);
					while (token_sigRef == "[[/transaction]]" && end_sigRef == 0) begin
						ap_c_n_tvin_trans_num_sigRef = ap_c_n_tvin_trans_num_sigRef + 1;
						read_token(fp_sigRef, token_sigRef); // should be [[transaction]] or [[[/runtime]]]
						if (token_sigRef == "[[[/runtime]]]") begin
							$fclose(fp_sigRef);
							end_sigRef = 1;
						end else begin
							end_sigRef = 0;
							read_token(fp_sigRef, token_sigRef); // should be transaction number
							read_token(fp_sigRef, token_sigRef);
						end
					end
				end
			end else begin
				ap_c_n_tvin_trans_num_sigRef = ap_c_n_tvin_trans_num_sigRef + 1;
			end
		end
	end
	
	`define STREAM_SIZE_IN_prealign_V "./stream_size_in_prealign_V.dat"
	
	initial begin : gen_ap_c_n_tvin_trans_num_prealign_V
		integer fp_prealign_V;
		reg [127:0] token_prealign_V;
		integer ret;
		
		ap_c_n_tvin_trans_num_prealign_V = 0;
		end_prealign_V = 0;
		wait (AESL_reset === 1);
		
		fp_prealign_V = $fopen(`AUTOTB_TVIN_prealign_V, "r");
		if(fp_prealign_V == 0) begin
			$display("Failed to open file \"%s\"!", `AUTOTB_TVIN_prealign_V);
			$finish;
		end
		read_token(fp_prealign_V, token_prealign_V); // should be [[[runtime]]]
		if (token_prealign_V != "[[[runtime]]]") begin
			$display("ERROR: token_prealign_V != \"[[[runtime]]]\"");
			$finish;
		end
		ap_c_n_tvin_trans_num_prealign_V = ap_c_n_tvin_trans_num_prealign_V + 1;
		read_token(fp_prealign_V, token_prealign_V); // should be [[transaction]] or [[[/runtime]]]
		if (token_prealign_V == "[[[/runtime]]]") begin
			$fclose(fp_prealign_V);
			end_prealign_V = 1;
		end else begin
			end_prealign_V = 0;
			read_token(fp_prealign_V, token_prealign_V); // should be transaction number
			read_token(fp_prealign_V, token_prealign_V);
		end
		while (token_prealign_V == "[[/transaction]]" && end_prealign_V == 0) begin
			ap_c_n_tvin_trans_num_prealign_V = ap_c_n_tvin_trans_num_prealign_V + 1;
			read_token(fp_prealign_V, token_prealign_V); // should be [[transaction]] or [[[/runtime]]]
			if (token_prealign_V == "[[[/runtime]]]") begin
				$fclose(fp_prealign_V);
				end_prealign_V = 1;
			end else begin
				end_prealign_V = 0;
				read_token(fp_prealign_V, token_prealign_V); // should be transaction number
				read_token(fp_prealign_V, token_prealign_V);
			end
		end
		forever begin
			@ (posedge AESL_clock);
			if (end_prealign_V == 0) begin
				if (prealign_V_TREADY == 1) begin
					read_token(fp_prealign_V, token_prealign_V);
					while (token_prealign_V == "[[/transaction]]" && end_prealign_V == 0) begin
						ap_c_n_tvin_trans_num_prealign_V = ap_c_n_tvin_trans_num_prealign_V + 1;
						read_token(fp_prealign_V, token_prealign_V); // should be [[transaction]] or [[[/runtime]]]
						if (token_prealign_V == "[[[/runtime]]]") begin
							$fclose(fp_prealign_V);
							end_prealign_V = 1;
						end else begin
							end_prealign_V = 0;
							read_token(fp_prealign_V, token_prealign_V); // should be transaction number
							read_token(fp_prealign_V, token_prealign_V);
						end
					end
				end
			end else begin
				ap_c_n_tvin_trans_num_prealign_V = ap_c_n_tvin_trans_num_prealign_V + 1;
			end
		end
	end
	

reg dump_tvout_finish_cmp;

initial begin : dump_tvout_runtime_sign_cmp
	integer fp;
	dump_tvout_finish_cmp = 0;
	fp = $fopen(`AUTOTB_TVOUT_cmp_out_wrapc, "w");
	if (fp == 0) begin
		$display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_cmp_out_wrapc);
		$display("ERROR: Simulation using HLS TB failed.");
		$finish;
	end
	$fdisplay(fp,"[[[runtime]]]");
	$fclose(fp);
	wait (done_cnt == `AUTOTB_TRANSACTION_NUM);
	// last transaction is saved at negedge right after last done
	@ (posedge AESL_clock);
	@ (posedge AESL_clock);
	@ (posedge AESL_clock);
	fp = $fopen(`AUTOTB_TVOUT_cmp_out_wrapc, "a");
	if (fp == 0) begin
		$display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_cmp_out_wrapc);
		$display("ERROR: Simulation using HLS TB failed.");
		$finish;
	end
	$fdisplay(fp,"[[[/runtime]]]");
	$fclose(fp);
	dump_tvout_finish_cmp = 1;
end

always @ (negedge AESL_clock) begin
    if(AESL_reset === 0)
    begin
        AESL_clk_counter <= 0;
    end 
    else begin
        AESL_clk_counter = AESL_clk_counter + 1;
    end
end

always @ (posedge AESL_clock or negedge AESL_reset) begin
	if (~AESL_reset) begin
		AESL_mLatCnterOut_addr = 0;
		AESL_mLatCnterOut[AESL_mLatCnterOut_addr] = AESL_clk_counter + 1;
	end else if (AESL_done && AESL_mLatCnterOut_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
		AESL_mLatCnterOut[AESL_mLatCnterOut_addr] = AESL_clk_counter;
		AESL_mLatCnterOut_addr = AESL_mLatCnterOut_addr + 1;
	end
end
always @ (posedge AESL_clock or negedge AESL_reset) begin
	if (~AESL_reset) begin
		reported_stuck_cnt <= 0;
	end else if (AESL_done && AESL_mLatCnterOut_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
		reported_stuck <= 0;
	end
end
always @ (posedge AESL_clock or negedge AESL_reset) begin
	if (~AESL_reset) begin
		AESL_mLatCnterIn_addr = 0;
	end else begin
		if (AESL_start && AESL_mLatCnterIn_addr == 0) begin
			AESL_mLatCnterIn[AESL_mLatCnterIn_addr] = AESL_clk_counter;
			AESL_mLatCnterIn_addr = AESL_mLatCnterIn_addr + 1;
		end else if (AESL_ready && AESL_mLatCnterIn_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
			AESL_mLatCnterIn[AESL_mLatCnterIn_addr] = AESL_clk_counter;
			AESL_mLatCnterIn_addr = AESL_mLatCnterIn_addr + 1;
		end
	end
end

initial begin : performance_check
	integer transaction_counter;
	integer i;
	integer fp;

	integer latthistime;
	integer lattotal;
	integer latmax;
	integer latmin;


	integer thrthistime;
	integer thrtotal;
	integer thrmax;
	integer thrmin;

	integer lataver;
	integer thraver;
	reg [31 : 0] lat_array [0 : `AUTOTB_TRANSACTION_NUM];
	reg [31 : 0] thr_array [0 : `AUTOTB_TRANSACTION_NUM];

	i = 0;
	lattotal = 0;
	latmax = 0;
	latmin = 32'h 7fffffff;
	lataver = 0;

	thrtotal = 0;
	thrmax = 0;
	thrmin = 32'h 7fffffff;
	thraver = 0;

	@(negedge AESL_clock);

	@(posedge AESL_reset);
	while (done_cnt < `AUTOTB_TRANSACTION_NUM) begin
		@(posedge AESL_clock);
	end

	#0.001

	for (i = 0; i < `AUTOTB_TRANSACTION_NUM; i = i + 1) begin
		latthistime = AESL_mLatCnterOut[i] - AESL_mLatCnterIn[i];
		lat_array[i] = latthistime;
		if (latthistime > latmax) latmax = latthistime;
		if (latthistime < latmin) latmin = latthistime;
		lattotal = lattotal + latthistime;
		if (`AUTOTB_TRANSACTION_NUM == 1) begin
			thrthistime = latthistime;
		end else begin
			thrthistime = AESL_mLatCnterIn[i + 1] - AESL_mLatCnterIn[i];
		end
		thr_array[i] = thrthistime;
		if (thrthistime > thrmax) thrmax = thrthistime;
		if (thrthistime < thrmin) thrmin = thrthistime;
		thrtotal = thrtotal + thrthistime;
	end

	lataver = lattotal / `AUTOTB_TRANSACTION_NUM;
	thraver = thrtotal / `AUTOTB_TRANSACTION_NUM;

	fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

	if (`AUTOTB_TRANSACTION_NUM == 1) begin
		thrmax  = 0;
		thrmin  = 0;
		thraver = 0;
		$fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latmax);
		$fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latmin);
		$fdisplay(fp, "$AVER_LATENCY = \"%0d\"", lataver);
		$fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", thrmax);
		$fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", thrmin);
		$fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", thraver);
	end else begin
		// $::AESL_AUTOSIM::gDataflowTaskPipelineFlag && $::AESL_AUTOSIM::gnoPortSwitchingFlag == 0
		$fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latmax );
		$fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latmin );
		$fdisplay(fp, "$AVER_LATENCY = \"%0d\"", lataver );
		$fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", thrmax );
		$fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", thrmin );
		$fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", thraver );
	end

	$fclose(fp);

	fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");
	$fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
	if (`AUTOTB_TRANSACTION_NUM == 1) begin
		i = 0;
		thr_array[i] = 0;
		$fdisplay(fp, "transaction%8d:%16d%16d", i, lat_array[i], thr_array[i]);
	end else begin
		for (i = 0; i < AESL_mLatCnterOut_addr; i = i + 1) begin
			$fdisplay(fp, "transaction%8d:%16d%16d", i, lat_array[i], thr_array[i]);
		end
	end
	$fclose(fp);
end

endmodule
