-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pyrconstuct_top_Loop_5_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ifftPyrOut_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    ifftPyrOut_empty_n : IN STD_LOGIC;
    ifftPyrOut_read : OUT STD_LOGIC;
    pyrFilOut_V_M_real_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    pyrFilOut_V_M_real_V_TVALID : OUT STD_LOGIC;
    pyrFilOut_V_M_real_V_TREADY : IN STD_LOGIC;
    pyrFilOut_V_M_imag_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    pyrFilOut_V_M_imag_V_TVALID : OUT STD_LOGIC;
    pyrFilOut_V_M_imag_V_TREADY : IN STD_LOGIC );
end;


architecture behav of pyrconstuct_top_Loop_5_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_pp0_stg0_fsm_1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_st4_fsm_2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_22 : BOOLEAN;
    signal i7_reg_76 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond_fu_87_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_reg_173 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_48 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_sig_bdd_56 : BOOLEAN;
    signal ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal i_fu_93_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_bdd_73 : BOOLEAN;
    signal ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY : STD_LOGIC := '0';
    signal ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY : STD_LOGIC := '0';
    signal tmp_9_fu_99_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_113_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_cast_fu_121_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_2_cast_fu_109_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_131_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_145_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_cast_fu_153_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_4_cast_fu_141_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_s_fu_125_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_2_fu_157_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_169 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_bdd_190 : BOOLEAN;
    signal ap_sig_bdd_189 : BOOLEAN;
    signal ap_sig_bdd_193 : BOOLEAN;


begin




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY assign process. --
    ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_189) then
                    if (not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) then 
                        ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_0;
                    elsif (ap_sig_bdd_190) then 
                        ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY assign process. --
    ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_189) then
                    if (not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) then 
                        ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_0;
                    elsif (ap_sig_bdd_193) then 
                        ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond_fu_87_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_73))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (exitcond_fu_87_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_73)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond_fu_87_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- i7_reg_76 assign process. --
    i7_reg_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (exitcond_fu_87_p2 = ap_const_lv1_0))) then 
                i7_reg_76 <= i_fu_93_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_73))) then 
                i7_reg_76 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                exitcond_reg_173 <= exitcond_fu_87_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, exitcond_fu_87_p2, exitcond_reg_173, ap_reg_ppiten_pp0_it0, ap_sig_bdd_56, ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY, ap_reg_ppiten_pp0_it1, ap_sig_bdd_73)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_73)) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_pp0_stg0_fsm_1 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond_fu_87_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond_fu_87_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                end if;
            when ap_ST_st4_fsm_2 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st4_fsm_2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st4_fsm_2)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_169 assign process. --
    ap_sig_bdd_169_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_169 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_189 assign process. --
    ap_sig_bdd_189_assign_proc : process(exitcond_reg_173, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1)
    begin
                ap_sig_bdd_189 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1));
    end process;


    -- ap_sig_bdd_190 assign process. --
    ap_sig_bdd_190_assign_proc : process(pyrFilOut_V_M_imag_V_TREADY, ap_sig_bdd_56, ap_reg_ppiten_pp0_it1)
    begin
                ap_sig_bdd_190 <= (not((ap_sig_bdd_56 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_logic_1 = pyrFilOut_V_M_imag_V_TREADY));
    end process;


    -- ap_sig_bdd_193 assign process. --
    ap_sig_bdd_193_assign_proc : process(pyrFilOut_V_M_real_V_TREADY, ap_sig_bdd_56, ap_reg_ppiten_pp0_it1)
    begin
                ap_sig_bdd_193 <= (not((ap_sig_bdd_56 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_logic_1 = pyrFilOut_V_M_real_V_TREADY));
    end process;


    -- ap_sig_bdd_22 assign process. --
    ap_sig_bdd_22_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_22 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_48 assign process. --
    ap_sig_bdd_48_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_48 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_56 assign process. --
    ap_sig_bdd_56_assign_proc : process(ifftPyrOut_empty_n, exitcond_reg_173)
    begin
                ap_sig_bdd_56 <= ((ifftPyrOut_empty_n = ap_const_logic_0) and (exitcond_reg_173 = ap_const_lv1_0));
    end process;


    -- ap_sig_bdd_73 assign process. --
    ap_sig_bdd_73_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_73 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_1_assign_proc : process(ap_sig_bdd_48)
    begin
        if (ap_sig_bdd_48) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_22)
    begin
        if (ap_sig_bdd_22) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st4_fsm_2 assign process. --
    ap_sig_cseq_ST_st4_fsm_2_assign_proc : process(ap_sig_bdd_169)
    begin
        if (ap_sig_bdd_169) then 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY assign process. --
    ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY_assign_proc : process(pyrFilOut_V_M_real_V_TREADY, ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY)) then 
            ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY <= pyrFilOut_V_M_real_V_TREADY;
        else 
            ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    exitcond_fu_87_p2 <= "1" when (i7_reg_76 = ap_const_lv10_200) else "0";
    i_fu_93_p2 <= std_logic_vector(unsigned(i7_reg_76) + unsigned(ap_const_lv10_1));

    -- ifftPyrOut_read assign process. --
    ifftPyrOut_read_assign_proc : process(exitcond_reg_173, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_sig_bdd_56, ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_56 or ((exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            ifftPyrOut_read <= ap_const_logic_1;
        else 
            ifftPyrOut_read <= ap_const_logic_0;
        end if; 
    end process;

        p_Val2_2_cast_fu_109_p1 <= std_logic_vector(resize(signed(tmp_9_fu_99_p4),15));

    p_Val2_2_fu_157_p2 <= std_logic_vector(unsigned(tmp_34_cast_fu_153_p1) + unsigned(p_Val2_4_cast_fu_141_p1));
        p_Val2_4_cast_fu_141_p1 <= std_logic_vector(resize(signed(tmp_1_fu_131_p4),15));

    p_Val2_s_fu_125_p2 <= std_logic_vector(unsigned(tmp_31_cast_fu_121_p1) + unsigned(p_Val2_2_cast_fu_109_p1));
        pyrFilOut_V_M_imag_V_TDATA <= std_logic_vector(resize(signed(p_Val2_2_fu_157_p2),24));


    -- pyrFilOut_V_M_imag_V_TVALID assign process. --
    pyrFilOut_V_M_imag_V_TVALID_assign_proc : process(exitcond_reg_173, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_sig_bdd_56, ap_reg_ppiten_pp0_it1, ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_56 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_logic_0 = ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY))) then 
            pyrFilOut_V_M_imag_V_TVALID <= ap_const_logic_1;
        else 
            pyrFilOut_V_M_imag_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

        pyrFilOut_V_M_real_V_TDATA <= std_logic_vector(resize(signed(p_Val2_s_fu_125_p2),24));


    -- pyrFilOut_V_M_real_V_TVALID assign process. --
    pyrFilOut_V_M_real_V_TVALID_assign_proc : process(exitcond_reg_173, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_sig_bdd_56, ap_reg_ppiten_pp0_it1, ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_reg_173 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_56 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_logic_0 = ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY))) then 
            pyrFilOut_V_M_real_V_TVALID <= ap_const_logic_1;
        else 
            pyrFilOut_V_M_real_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_131_p4 <= ifftPyrOut_dout(47 downto 34);
    tmp_2_fu_145_p3 <= ifftPyrOut_dout(33 downto 33);
    tmp_31_cast_fu_121_p1 <= std_logic_vector(resize(unsigned(tmp_fu_113_p3),15));
    tmp_34_cast_fu_153_p1 <= std_logic_vector(resize(unsigned(tmp_2_fu_145_p3),15));
    tmp_9_fu_99_p4 <= ifftPyrOut_dout(23 downto 10);
    tmp_fu_113_p3 <= ifftPyrOut_dout(9 downto 9);
end behav;
