// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _cmpy_complex_top_Loop_1_proc143_HH_
#define _cmpy_complex_top_Loop_1_proc143_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cmpy_complex_top_myatan2_complex_ap_fixed_s.h"

namespace ap_rtl {

struct cmpy_complex_top_Loop_1_proc143 : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > nL;
    sc_out< sc_lv<11> > refAtans_V_address0;
    sc_out< sc_logic > refAtans_V_ce0;
    sc_out< sc_logic > refAtans_V_we0;
    sc_out< sc_lv<20> > refAtans_V_d0;
    sc_in< sc_lv<24> > sigRef_TDATA;
    sc_in< sc_logic > sigRef_TVALID;
    sc_out< sc_logic > sigRef_TREADY;
    sc_in< sc_lv<10> > factor_V;
    sc_out< sc_lv<32> > nL_out_din;
    sc_in< sc_logic > nL_out_full_n;
    sc_out< sc_logic > nL_out_write;
    sc_out< sc_lv<10> > factor_V_out_din;
    sc_in< sc_logic > factor_V_out_full_n;
    sc_out< sc_logic > factor_V_out_write;


    // Module declarations
    cmpy_complex_top_Loop_1_proc143(sc_module_name name);
    SC_HAS_PROCESS(cmpy_complex_top_Loop_1_proc143);

    ~cmpy_complex_top_Loop_1_proc143();

    sc_trace_file* mVcdFile;

    cmpy_complex_top_myatan2_complex_ap_fixed_s* grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_22;
    sc_signal< sc_lv<31> > i_i_i_reg_90;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it1;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_bdd_57;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TDATA_blk_n;
    sc_signal< sc_lv<1> > tmp_i_i_reg_139;
    sc_signal< bool > ap_sig_bdd_68;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it7;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it8;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it9;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it10;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it11;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it12;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it2;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it3;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it4;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it5;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it6;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it7;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it8;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it9;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it10;
    sc_signal< sc_lv<31> > ap_reg_ppstg_i_i_i_reg_90_pp0_it11;
    sc_signal< sc_lv<32> > tmp_fu_108_p2;
    sc_signal< sc_lv<32> > tmp_reg_134;
    sc_signal< bool > ap_sig_bdd_115;
    sc_signal< sc_lv<1> > tmp_i_i_fu_118_p2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it5;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it6;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it7;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it8;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it9;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it10;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_i_i_reg_139_pp0_it11;
    sc_signal< sc_lv<31> > i_fu_123_p2;
    sc_signal< sc_lv<31> > i_reg_143;
    sc_signal< sc_lv<20> > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_return;
    sc_signal< sc_lv<20> > tmp_1980_i_i_reg_148;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_start;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_done;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_idle;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_ready;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TVALID;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_ce;
    sc_signal< sc_lv<24> > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TDATA;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TREADY;
    sc_signal< sc_lv<31> > i_i_i_phi_fu_94_p4;
    sc_signal< sc_logic > grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_start_ap_start_reg;
    sc_signal< sc_lv<64> > tmp_17_i_i_fu_129_p1;
    sc_signal< sc_lv<32> > i_cast_i_i_fu_114_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_2;
    sc_signal< bool > ap_sig_bdd_225;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st15_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_115();
    void thread_ap_sig_bdd_22();
    void thread_ap_sig_bdd_225();
    void thread_ap_sig_bdd_57();
    void thread_ap_sig_bdd_68();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st15_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_factor_V_out_din();
    void thread_factor_V_out_write();
    void thread_grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_ce();
    void thread_grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_ap_start();
    void thread_grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TDATA();
    void thread_grp_cmpy_complex_top_myatan2_complex_ap_fixed_s_fu_102_xin_TVALID();
    void thread_i_cast_i_i_fu_114_p1();
    void thread_i_fu_123_p2();
    void thread_i_i_i_phi_fu_94_p4();
    void thread_nL_out_din();
    void thread_nL_out_write();
    void thread_refAtans_V_address0();
    void thread_refAtans_V_ce0();
    void thread_refAtans_V_d0();
    void thread_refAtans_V_we0();
    void thread_sigRef_TREADY();
    void thread_tmp_17_i_i_fu_129_p1();
    void thread_tmp_fu_108_p2();
    void thread_tmp_i_i_fu_118_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
