// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pyrconstuct_top_Loop_5_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ifftPyrOut_dout,
        ifftPyrOut_empty_n,
        ifftPyrOut_read,
        pyrFilOut_V_M_real_V_TDATA,
        pyrFilOut_V_M_real_V_TVALID,
        pyrFilOut_V_M_real_V_TREADY,
        pyrFilOut_V_M_imag_V_TDATA,
        pyrFilOut_V_M_imag_V_TVALID,
        pyrFilOut_V_M_imag_V_TREADY
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st4_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv10_200 = 10'b1000000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] ifftPyrOut_dout;
input   ifftPyrOut_empty_n;
output   ifftPyrOut_read;
output  [23:0] pyrFilOut_V_M_real_V_TDATA;
output   pyrFilOut_V_M_real_V_TVALID;
input   pyrFilOut_V_M_real_V_TREADY;
output  [23:0] pyrFilOut_V_M_imag_V_TDATA;
output   pyrFilOut_V_M_imag_V_TVALID;
input   pyrFilOut_V_M_imag_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ifftPyrOut_read;
reg pyrFilOut_V_M_real_V_TVALID;
reg pyrFilOut_V_M_imag_V_TVALID;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [9:0] i7_reg_76;
wire   [0:0] exitcond_fu_87_p2;
reg   [0:0] exitcond_reg_173;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_48;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_56;
reg    ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [9:0] i_fu_93_p2;
reg    ap_sig_bdd_73;
reg    ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY = 1'b0;
reg    ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY = 1'b0;
wire   [13:0] tmp_9_fu_99_p4;
wire   [0:0] tmp_fu_113_p3;
wire   [14:0] tmp_31_cast_fu_121_p1;
wire  signed [14:0] p_Val2_2_cast_fu_109_p1;
wire   [13:0] tmp_1_fu_131_p4;
wire   [0:0] tmp_2_fu_145_p3;
wire   [14:0] tmp_34_cast_fu_153_p1;
wire  signed [14:0] p_Val2_4_cast_fu_141_p1;
wire   [14:0] p_Val2_s_fu_125_p2;
wire   [14:0] p_Val2_2_fu_157_p2;
reg    ap_sig_cseq_ST_st4_fsm_2;
reg    ap_sig_bdd_169;
reg   [2:0] ap_NS_fsm;
reg    ap_sig_bdd_190;
reg    ap_sig_bdd_189;
reg    ap_sig_bdd_193;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_2)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_0;
    end else begin
        if (ap_sig_bdd_189) begin
            if (~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_0;
            end else if (ap_sig_bdd_190) begin
                ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY <= ap_const_logic_1;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_0;
    end else begin
        if (ap_sig_bdd_189) begin
            if (~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_0;
            end else if (ap_sig_bdd_193) begin
                ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY <= ap_const_logic_1;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_87_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_73)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond_fu_87_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_73) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_87_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond_fu_87_p2 == ap_const_lv1_0))) begin
        i7_reg_76 <= i_fu_93_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_73)) begin
        i7_reg_76 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        exitcond_reg_173 <= exitcond_fu_87_p2;
    end
end

always @ (ap_done_reg or ap_sig_cseq_ST_st4_fsm_2) begin
    if (((ap_const_logic_1 == ap_done_reg) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_2)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_48) begin
    if (ap_sig_bdd_48) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_169) begin
    if (ap_sig_bdd_169) begin
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_0;
    end
end

always @ (pyrFilOut_V_M_real_V_TREADY or ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY)) begin
        ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY = pyrFilOut_V_M_real_V_TREADY;
    end else begin
        ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY = ap_const_logic_1;
    end
end

always @ (exitcond_reg_173 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_sig_bdd_56 or ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY or ap_reg_ppiten_pp0_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ifftPyrOut_read = ap_const_logic_1;
    end else begin
        ifftPyrOut_read = ap_const_logic_0;
    end
end

always @ (exitcond_reg_173 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_sig_bdd_56 or ap_reg_ppiten_pp0_it1 or ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_56 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_pyrFilOut_V_M_imag_V_TREADY))) begin
        pyrFilOut_V_M_imag_V_TVALID = ap_const_logic_1;
    end else begin
        pyrFilOut_V_M_imag_V_TVALID = ap_const_logic_0;
    end
end

always @ (exitcond_reg_173 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_sig_bdd_56 or ap_reg_ppiten_pp0_it1 or ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_56 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_pyrFilOut_V_M_real_V_TREADY))) begin
        pyrFilOut_V_M_real_V_TVALID = ap_const_logic_1;
    end else begin
        pyrFilOut_V_M_real_V_TVALID = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or exitcond_fu_87_p2 or exitcond_reg_173 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_56 or ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_73) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_73) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_87_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_56 | ((exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_pyrFilOut_V_M_real_V_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_87_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st4_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st4_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_169 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (exitcond_reg_173 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1) begin
    ap_sig_bdd_189 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_reg_173 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1));
end


always @ (pyrFilOut_V_M_imag_V_TREADY or ap_sig_bdd_56 or ap_reg_ppiten_pp0_it1) begin
    ap_sig_bdd_190 = (~(ap_sig_bdd_56 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_1 == pyrFilOut_V_M_imag_V_TREADY));
end


always @ (pyrFilOut_V_M_real_V_TREADY or ap_sig_bdd_56 or ap_reg_ppiten_pp0_it1) begin
    ap_sig_bdd_193 = (~(ap_sig_bdd_56 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_1 == pyrFilOut_V_M_real_V_TREADY));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_48 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ifftPyrOut_empty_n or exitcond_reg_173) begin
    ap_sig_bdd_56 = ((ifftPyrOut_empty_n == ap_const_logic_0) & (exitcond_reg_173 == ap_const_lv1_0));
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_73 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

assign exitcond_fu_87_p2 = (i7_reg_76 == ap_const_lv10_200? 1'b1: 1'b0);

assign i_fu_93_p2 = (i7_reg_76 + ap_const_lv10_1);

assign p_Val2_2_cast_fu_109_p1 = $signed(tmp_9_fu_99_p4);

assign p_Val2_2_fu_157_p2 = ($signed(tmp_34_cast_fu_153_p1) + $signed(p_Val2_4_cast_fu_141_p1));

assign p_Val2_4_cast_fu_141_p1 = $signed(tmp_1_fu_131_p4);

assign p_Val2_s_fu_125_p2 = ($signed(tmp_31_cast_fu_121_p1) + $signed(p_Val2_2_cast_fu_109_p1));

assign pyrFilOut_V_M_imag_V_TDATA = $signed(p_Val2_2_fu_157_p2);

assign pyrFilOut_V_M_real_V_TDATA = $signed(p_Val2_s_fu_125_p2);

assign tmp_1_fu_131_p4 = {{ifftPyrOut_dout[ap_const_lv32_2F : ap_const_lv32_22]}};

assign tmp_2_fu_145_p3 = ifftPyrOut_dout[ap_const_lv32_21];

assign tmp_31_cast_fu_121_p1 = tmp_fu_113_p3;

assign tmp_34_cast_fu_153_p1 = tmp_2_fu_145_p3;

assign tmp_9_fu_99_p4 = {{ifftPyrOut_dout[ap_const_lv32_17 : ap_const_lv32_A]}};

assign tmp_fu_113_p3 = ifftPyrOut_dout[ap_const_lv32_9];


endmodule //pyrconstuct_top_Loop_5_proc

