// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "pyrconstuct_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pyrconstuct_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<40> pyrconstuct_top::ap_const_lv40_0 = "0000000000000000000000000000000000000000";
const sc_logic pyrconstuct_top::ap_const_logic_0 = sc_dt::Log_0;
const bool pyrconstuct_top::ap_true = true;
const sc_lv<24> pyrconstuct_top::ap_const_lv24_0 = "000000000000000000000000";

pyrconstuct_top::pyrconstuct_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    imgOutTmpBlockRam_M_real_V_U = new pyrconstuct_top_imgOutTmpBlockRam_M_real_V("imgOutTmpBlockRam_M_real_V_U");
    imgOutTmpBlockRam_M_real_V_U->clk(ap_clk);
    imgOutTmpBlockRam_M_real_V_U->reset(ap_rst_n_inv);
    imgOutTmpBlockRam_M_real_V_U->i_address0(imgOutTmpBlockRam_M_real_V_i_address0);
    imgOutTmpBlockRam_M_real_V_U->i_ce0(imgOutTmpBlockRam_M_real_V_i_ce0);
    imgOutTmpBlockRam_M_real_V_U->i_we0(imgOutTmpBlockRam_M_real_V_i_we0);
    imgOutTmpBlockRam_M_real_V_U->i_d0(imgOutTmpBlockRam_M_real_V_i_d0);
    imgOutTmpBlockRam_M_real_V_U->i_q0(imgOutTmpBlockRam_M_real_V_i_q0);
    imgOutTmpBlockRam_M_real_V_U->t_address0(imgOutTmpBlockRam_M_real_V_t_address0);
    imgOutTmpBlockRam_M_real_V_U->t_ce0(imgOutTmpBlockRam_M_real_V_t_ce0);
    imgOutTmpBlockRam_M_real_V_U->t_we0(imgOutTmpBlockRam_M_real_V_t_we0);
    imgOutTmpBlockRam_M_real_V_U->t_d0(imgOutTmpBlockRam_M_real_V_t_d0);
    imgOutTmpBlockRam_M_real_V_U->t_q0(imgOutTmpBlockRam_M_real_V_t_q0);
    imgOutTmpBlockRam_M_real_V_U->i_ce(imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce);
    imgOutTmpBlockRam_M_real_V_U->t_ce(imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce);
    imgOutTmpBlockRam_M_real_V_U->i_full_n(imgOutTmpBlockRam_M_real_V_i_full_n);
    imgOutTmpBlockRam_M_real_V_U->i_write(imgOutTmpBlockRam_M_real_V_i_write);
    imgOutTmpBlockRam_M_real_V_U->t_empty_n(imgOutTmpBlockRam_M_real_V_t_empty_n);
    imgOutTmpBlockRam_M_real_V_U->t_read(imgOutTmpBlockRam_M_real_V_t_read);
    imgOutTmpBlockRam_M_imag_V_U = new pyrconstuct_top_imgOutTmpBlockRam_M_real_V("imgOutTmpBlockRam_M_imag_V_U");
    imgOutTmpBlockRam_M_imag_V_U->clk(ap_clk);
    imgOutTmpBlockRam_M_imag_V_U->reset(ap_rst_n_inv);
    imgOutTmpBlockRam_M_imag_V_U->i_address0(imgOutTmpBlockRam_M_imag_V_i_address0);
    imgOutTmpBlockRam_M_imag_V_U->i_ce0(imgOutTmpBlockRam_M_imag_V_i_ce0);
    imgOutTmpBlockRam_M_imag_V_U->i_we0(imgOutTmpBlockRam_M_imag_V_i_we0);
    imgOutTmpBlockRam_M_imag_V_U->i_d0(imgOutTmpBlockRam_M_imag_V_i_d0);
    imgOutTmpBlockRam_M_imag_V_U->i_q0(imgOutTmpBlockRam_M_imag_V_i_q0);
    imgOutTmpBlockRam_M_imag_V_U->t_address0(imgOutTmpBlockRam_M_imag_V_t_address0);
    imgOutTmpBlockRam_M_imag_V_U->t_ce0(imgOutTmpBlockRam_M_imag_V_t_ce0);
    imgOutTmpBlockRam_M_imag_V_U->t_we0(imgOutTmpBlockRam_M_imag_V_t_we0);
    imgOutTmpBlockRam_M_imag_V_U->t_d0(imgOutTmpBlockRam_M_imag_V_t_d0);
    imgOutTmpBlockRam_M_imag_V_U->t_q0(imgOutTmpBlockRam_M_imag_V_t_q0);
    imgOutTmpBlockRam_M_imag_V_U->i_ce(imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce);
    imgOutTmpBlockRam_M_imag_V_U->t_ce(imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce);
    imgOutTmpBlockRam_M_imag_V_U->i_full_n(imgOutTmpBlockRam_M_imag_V_i_full_n);
    imgOutTmpBlockRam_M_imag_V_U->i_write(imgOutTmpBlockRam_M_imag_V_i_write);
    imgOutTmpBlockRam_M_imag_V_U->t_empty_n(imgOutTmpBlockRam_M_imag_V_t_empty_n);
    imgOutTmpBlockRam_M_imag_V_U->t_read(imgOutTmpBlockRam_M_imag_V_t_read);
    pyrconstuct_top_Block_codeRepl26_proc_U0 = new pyrconstuct_top_Block_codeRepl26_proc("pyrconstuct_top_Block_codeRepl26_proc_U0");
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_start(pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_done(pyrconstuct_top_Block_codeRepl26_proc_U0_ap_done);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_continue(pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_idle(pyrconstuct_top_Block_codeRepl26_proc_U0_ap_idle);
    pyrconstuct_top_Block_codeRepl26_proc_U0->ap_ready(pyrconstuct_top_Block_codeRepl26_proc_U0_ap_ready);
    pyrconstuct_top_Block_codeRepl26_proc_U0->fft_config_data_V_din(pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_din);
    pyrconstuct_top_Block_codeRepl26_proc_U0->fft_config_data_V_full_n(pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n);
    pyrconstuct_top_Block_codeRepl26_proc_U0->fft_config_data_V_write(pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_write);
    pyrconstuct_top_Loop_1_proc_U0 = new pyrconstuct_top_Loop_1_proc("pyrconstuct_top_Loop_1_proc_U0");
    pyrconstuct_top_Loop_1_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Loop_1_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Loop_1_proc_U0->ap_start(pyrconstuct_top_Loop_1_proc_U0_ap_start);
    pyrconstuct_top_Loop_1_proc_U0->ap_done(pyrconstuct_top_Loop_1_proc_U0_ap_done);
    pyrconstuct_top_Loop_1_proc_U0->ap_continue(pyrconstuct_top_Loop_1_proc_U0_ap_continue);
    pyrconstuct_top_Loop_1_proc_U0->ap_idle(pyrconstuct_top_Loop_1_proc_U0_ap_idle);
    pyrconstuct_top_Loop_1_proc_U0->ap_ready(pyrconstuct_top_Loop_1_proc_U0_ap_ready);
    pyrconstuct_top_Loop_1_proc_U0->imgIn_TDATA(pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA);
    pyrconstuct_top_Loop_1_proc_U0->imgIn_TVALID(pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID);
    pyrconstuct_top_Loop_1_proc_U0->imgIn_TREADY(pyrconstuct_top_Loop_1_proc_U0_imgIn_TREADY);
    pyrconstuct_top_Loop_1_proc_U0->imgInTmp_din(pyrconstuct_top_Loop_1_proc_U0_imgInTmp_din);
    pyrconstuct_top_Loop_1_proc_U0->imgInTmp_full_n(pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n);
    pyrconstuct_top_Loop_1_proc_U0->imgInTmp_write(pyrconstuct_top_Loop_1_proc_U0_imgInTmp_write);
    fft_config1_U0 = new fft_config1_s("fft_config1_U0");
    fft_config1_U0->ap_clk(ap_clk);
    fft_config1_U0->ap_rst(ap_rst_n_inv);
    fft_config1_U0->ap_start(fft_config1_U0_ap_start);
    fft_config1_U0->ap_ce(fft_config1_U0_ap_ce);
    fft_config1_U0->ap_done(fft_config1_U0_ap_done);
    fft_config1_U0->ap_idle(fft_config1_U0_ap_idle);
    fft_config1_U0->ap_ready(fft_config1_U0_ap_ready);
    fft_config1_U0->xn_dout(fft_config1_U0_xn_dout);
    fft_config1_U0->xn_empty_n(fft_config1_U0_xn_empty_n);
    fft_config1_U0->xn_read(fft_config1_U0_xn_read);
    fft_config1_U0->xk_din(fft_config1_U0_xk_din);
    fft_config1_U0->xk_full_n(fft_config1_U0_xk_full_n);
    fft_config1_U0->xk_write(fft_config1_U0_xk_write);
    fft_config1_U0->status_data_V_din(fft_config1_U0_status_data_V_din);
    fft_config1_U0->status_data_V_full_n(fft_config1_U0_status_data_V_full_n);
    fft_config1_U0->status_data_V_write(fft_config1_U0_status_data_V_write);
    fft_config1_U0->config_ch_data_V_dout(fft_config1_U0_config_ch_data_V_dout);
    fft_config1_U0->config_ch_data_V_empty_n(fft_config1_U0_config_ch_data_V_empty_n);
    fft_config1_U0->config_ch_data_V_read(fft_config1_U0_config_ch_data_V_read);
    pyrconstuct_top_Loop_2_proc_U0 = new pyrconstuct_top_Loop_2_proc("pyrconstuct_top_Loop_2_proc_U0");
    pyrconstuct_top_Loop_2_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Loop_2_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Loop_2_proc_U0->ap_start(pyrconstuct_top_Loop_2_proc_U0_ap_start);
    pyrconstuct_top_Loop_2_proc_U0->ap_done(pyrconstuct_top_Loop_2_proc_U0_ap_done);
    pyrconstuct_top_Loop_2_proc_U0->ap_continue(pyrconstuct_top_Loop_2_proc_U0_ap_continue);
    pyrconstuct_top_Loop_2_proc_U0->ap_idle(pyrconstuct_top_Loop_2_proc_U0_ap_idle);
    pyrconstuct_top_Loop_2_proc_U0->ap_ready(pyrconstuct_top_Loop_2_proc_U0_ap_ready);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpFFTStream_dout(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpFFTStream_empty_n(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpFFTStream_read(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_read);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_real_V_address0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_address0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_real_V_ce0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_ce0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_real_V_we0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_we0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_real_V_d0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_d0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_imag_V_address0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_address0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_imag_V_ce0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_imag_V_we0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_we0);
    pyrconstuct_top_Loop_2_proc_U0->imgOutTmpBlockRam_M_imag_V_d0(pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_d0);
    pyrconstuct_top_Loop_3_proc_U0 = new pyrconstuct_top_Loop_3_proc("pyrconstuct_top_Loop_3_proc_U0");
    pyrconstuct_top_Loop_3_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Loop_3_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Loop_3_proc_U0->ap_start(pyrconstuct_top_Loop_3_proc_U0_ap_start);
    pyrconstuct_top_Loop_3_proc_U0->ap_done(pyrconstuct_top_Loop_3_proc_U0_ap_done);
    pyrconstuct_top_Loop_3_proc_U0->ap_continue(pyrconstuct_top_Loop_3_proc_U0_ap_continue);
    pyrconstuct_top_Loop_3_proc_U0->ap_idle(pyrconstuct_top_Loop_3_proc_U0_ap_idle);
    pyrconstuct_top_Loop_3_proc_U0->ap_ready(pyrconstuct_top_Loop_3_proc_U0_ap_ready);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_real_V_address0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_address0);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_real_V_ce0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_ce0);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_real_V_q0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_imag_V_address0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_address0);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_imag_V_ce0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0);
    pyrconstuct_top_Loop_3_proc_U0->imgOutTmpBlockRam_M_imag_V_q0(pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_real_V_din(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_din);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_real_V_full_n(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_real_V_write(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_write);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_imag_V_din(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_din);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_imag_V_full_n(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n);
    pyrconstuct_top_Loop_3_proc_U0->fftPyrOut_M_imag_V_write(pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_write);
    pyrconstuct_top_Loop_4_proc_U0 = new pyrconstuct_top_Loop_4_proc("pyrconstuct_top_Loop_4_proc_U0");
    pyrconstuct_top_Loop_4_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Loop_4_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Loop_4_proc_U0->ap_start(pyrconstuct_top_Loop_4_proc_U0_ap_start);
    pyrconstuct_top_Loop_4_proc_U0->ap_done(pyrconstuct_top_Loop_4_proc_U0_ap_done);
    pyrconstuct_top_Loop_4_proc_U0->ap_continue(pyrconstuct_top_Loop_4_proc_U0_ap_continue);
    pyrconstuct_top_Loop_4_proc_U0->ap_idle(pyrconstuct_top_Loop_4_proc_U0_ap_idle);
    pyrconstuct_top_Loop_4_proc_U0->ap_ready(pyrconstuct_top_Loop_4_proc_U0_ap_ready);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_real_V_dout(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_real_V_empty_n(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_real_V_read(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_read);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_imag_V_dout(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_imag_V_empty_n(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n);
    pyrconstuct_top_Loop_4_proc_U0->fftPyrOut_M_imag_V_read(pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_read);
    pyrconstuct_top_Loop_4_proc_U0->imgInTmp2_din(pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_din);
    pyrconstuct_top_Loop_4_proc_U0->imgInTmp2_full_n(pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n);
    pyrconstuct_top_Loop_4_proc_U0->imgInTmp2_write(pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_write);
    pyrconstuct_top_Block_proc_U0 = new pyrconstuct_top_Block_proc("pyrconstuct_top_Block_proc_U0");
    pyrconstuct_top_Block_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Block_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Block_proc_U0->ap_start(pyrconstuct_top_Block_proc_U0_ap_start);
    pyrconstuct_top_Block_proc_U0->ap_done(pyrconstuct_top_Block_proc_U0_ap_done);
    pyrconstuct_top_Block_proc_U0->ap_continue(pyrconstuct_top_Block_proc_U0_ap_continue);
    pyrconstuct_top_Block_proc_U0->ap_idle(pyrconstuct_top_Block_proc_U0_ap_idle);
    pyrconstuct_top_Block_proc_U0->ap_ready(pyrconstuct_top_Block_proc_U0_ap_ready);
    pyrconstuct_top_Block_proc_U0->fft_config2_data_V_din(pyrconstuct_top_Block_proc_U0_fft_config2_data_V_din);
    pyrconstuct_top_Block_proc_U0->fft_config2_data_V_full_n(pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n);
    pyrconstuct_top_Block_proc_U0->fft_config2_data_V_write(pyrconstuct_top_Block_proc_U0_fft_config2_data_V_write);
    fft_config2_U0 = new fft_config2_s("fft_config2_U0");
    fft_config2_U0->ap_clk(ap_clk);
    fft_config2_U0->ap_rst(ap_rst_n_inv);
    fft_config2_U0->ap_start(fft_config2_U0_ap_start);
    fft_config2_U0->ap_ce(fft_config2_U0_ap_ce);
    fft_config2_U0->ap_done(fft_config2_U0_ap_done);
    fft_config2_U0->ap_idle(fft_config2_U0_ap_idle);
    fft_config2_U0->ap_ready(fft_config2_U0_ap_ready);
    fft_config2_U0->xn_dout(fft_config2_U0_xn_dout);
    fft_config2_U0->xn_empty_n(fft_config2_U0_xn_empty_n);
    fft_config2_U0->xn_read(fft_config2_U0_xn_read);
    fft_config2_U0->xk_din(fft_config2_U0_xk_din);
    fft_config2_U0->xk_full_n(fft_config2_U0_xk_full_n);
    fft_config2_U0->xk_write(fft_config2_U0_xk_write);
    fft_config2_U0->status_data_V_din(fft_config2_U0_status_data_V_din);
    fft_config2_U0->status_data_V_full_n(fft_config2_U0_status_data_V_full_n);
    fft_config2_U0->status_data_V_write(fft_config2_U0_status_data_V_write);
    fft_config2_U0->config_ch_data_V_dout(fft_config2_U0_config_ch_data_V_dout);
    fft_config2_U0->config_ch_data_V_empty_n(fft_config2_U0_config_ch_data_V_empty_n);
    fft_config2_U0->config_ch_data_V_read(fft_config2_U0_config_ch_data_V_read);
    pyrconstuct_top_Loop_5_proc_U0 = new pyrconstuct_top_Loop_5_proc("pyrconstuct_top_Loop_5_proc_U0");
    pyrconstuct_top_Loop_5_proc_U0->ap_clk(ap_clk);
    pyrconstuct_top_Loop_5_proc_U0->ap_rst(ap_rst_n_inv);
    pyrconstuct_top_Loop_5_proc_U0->ap_start(pyrconstuct_top_Loop_5_proc_U0_ap_start);
    pyrconstuct_top_Loop_5_proc_U0->ap_done(pyrconstuct_top_Loop_5_proc_U0_ap_done);
    pyrconstuct_top_Loop_5_proc_U0->ap_continue(pyrconstuct_top_Loop_5_proc_U0_ap_continue);
    pyrconstuct_top_Loop_5_proc_U0->ap_idle(pyrconstuct_top_Loop_5_proc_U0_ap_idle);
    pyrconstuct_top_Loop_5_proc_U0->ap_ready(pyrconstuct_top_Loop_5_proc_U0_ap_ready);
    pyrconstuct_top_Loop_5_proc_U0->ifftPyrOut_dout(pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout);
    pyrconstuct_top_Loop_5_proc_U0->ifftPyrOut_empty_n(pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n);
    pyrconstuct_top_Loop_5_proc_U0->ifftPyrOut_read(pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_read);
    pyrconstuct_top_Loop_5_proc_U0->pyrFilOut_V_TDATA(pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TDATA);
    pyrconstuct_top_Loop_5_proc_U0->pyrFilOut_V_TVALID(pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TVALID);
    pyrconstuct_top_Loop_5_proc_U0->pyrFilOut_V_TREADY(pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY);
    fft_config_data_V_channel_U = new FIFO_pyrconstuct_top_fft_config_data_V_channel("fft_config_data_V_channel_U");
    fft_config_data_V_channel_U->clk(ap_clk);
    fft_config_data_V_channel_U->reset(ap_rst_n_inv);
    fft_config_data_V_channel_U->if_read_ce(fft_config_data_V_channel_U_ap_dummy_ce);
    fft_config_data_V_channel_U->if_write_ce(fft_config_data_V_channel_U_ap_dummy_ce);
    fft_config_data_V_channel_U->if_din(fft_config_data_V_channel_din);
    fft_config_data_V_channel_U->if_full_n(fft_config_data_V_channel_full_n);
    fft_config_data_V_channel_U->if_write(fft_config_data_V_channel_write);
    fft_config_data_V_channel_U->if_dout(fft_config_data_V_channel_dout);
    fft_config_data_V_channel_U->if_empty_n(fft_config_data_V_channel_empty_n);
    fft_config_data_V_channel_U->if_read(fft_config_data_V_channel_read);
    imgInTmp_channel_U = new FIFO_pyrconstuct_top_imgInTmp_channel("imgInTmp_channel_U");
    imgInTmp_channel_U->clk(ap_clk);
    imgInTmp_channel_U->reset(ap_rst_n_inv);
    imgInTmp_channel_U->if_read_ce(imgInTmp_channel_U_ap_dummy_ce);
    imgInTmp_channel_U->if_write_ce(imgInTmp_channel_U_ap_dummy_ce);
    imgInTmp_channel_U->if_din(imgInTmp_channel_din);
    imgInTmp_channel_U->if_full_n(imgInTmp_channel_full_n);
    imgInTmp_channel_U->if_write(imgInTmp_channel_write);
    imgInTmp_channel_U->if_dout(imgInTmp_channel_dout);
    imgInTmp_channel_U->if_empty_n(imgInTmp_channel_empty_n);
    imgInTmp_channel_U->if_read(imgInTmp_channel_read);
    imgOutTmpFFTStream_channel_U = new FIFO_pyrconstuct_top_imgOutTmpFFTStream_channel("imgOutTmpFFTStream_channel_U");
    imgOutTmpFFTStream_channel_U->clk(ap_clk);
    imgOutTmpFFTStream_channel_U->reset(ap_rst_n_inv);
    imgOutTmpFFTStream_channel_U->if_read_ce(imgOutTmpFFTStream_channel_U_ap_dummy_ce);
    imgOutTmpFFTStream_channel_U->if_write_ce(imgOutTmpFFTStream_channel_U_ap_dummy_ce);
    imgOutTmpFFTStream_channel_U->if_din(imgOutTmpFFTStream_channel_din);
    imgOutTmpFFTStream_channel_U->if_full_n(imgOutTmpFFTStream_channel_full_n);
    imgOutTmpFFTStream_channel_U->if_write(imgOutTmpFFTStream_channel_write);
    imgOutTmpFFTStream_channel_U->if_dout(imgOutTmpFFTStream_channel_dout);
    imgOutTmpFFTStream_channel_U->if_empty_n(imgOutTmpFFTStream_channel_empty_n);
    imgOutTmpFFTStream_channel_U->if_read(imgOutTmpFFTStream_channel_read);
    fftPyrOut_M_real_V_U = new FIFO_pyrconstuct_top_fftPyrOut_M_real_V("fftPyrOut_M_real_V_U");
    fftPyrOut_M_real_V_U->clk(ap_clk);
    fftPyrOut_M_real_V_U->reset(ap_rst_n_inv);
    fftPyrOut_M_real_V_U->if_read_ce(fftPyrOut_M_real_V_U_ap_dummy_ce);
    fftPyrOut_M_real_V_U->if_write_ce(fftPyrOut_M_real_V_U_ap_dummy_ce);
    fftPyrOut_M_real_V_U->if_din(fftPyrOut_M_real_V_din);
    fftPyrOut_M_real_V_U->if_full_n(fftPyrOut_M_real_V_full_n);
    fftPyrOut_M_real_V_U->if_write(fftPyrOut_M_real_V_write);
    fftPyrOut_M_real_V_U->if_dout(fftPyrOut_M_real_V_dout);
    fftPyrOut_M_real_V_U->if_empty_n(fftPyrOut_M_real_V_empty_n);
    fftPyrOut_M_real_V_U->if_read(fftPyrOut_M_real_V_read);
    fftPyrOut_M_imag_V_U = new FIFO_pyrconstuct_top_fftPyrOut_M_imag_V("fftPyrOut_M_imag_V_U");
    fftPyrOut_M_imag_V_U->clk(ap_clk);
    fftPyrOut_M_imag_V_U->reset(ap_rst_n_inv);
    fftPyrOut_M_imag_V_U->if_read_ce(fftPyrOut_M_imag_V_U_ap_dummy_ce);
    fftPyrOut_M_imag_V_U->if_write_ce(fftPyrOut_M_imag_V_U_ap_dummy_ce);
    fftPyrOut_M_imag_V_U->if_din(fftPyrOut_M_imag_V_din);
    fftPyrOut_M_imag_V_U->if_full_n(fftPyrOut_M_imag_V_full_n);
    fftPyrOut_M_imag_V_U->if_write(fftPyrOut_M_imag_V_write);
    fftPyrOut_M_imag_V_U->if_dout(fftPyrOut_M_imag_V_dout);
    fftPyrOut_M_imag_V_U->if_empty_n(fftPyrOut_M_imag_V_empty_n);
    fftPyrOut_M_imag_V_U->if_read(fftPyrOut_M_imag_V_read);
    imgInTmp2_channel_U = new FIFO_pyrconstuct_top_imgInTmp2_channel("imgInTmp2_channel_U");
    imgInTmp2_channel_U->clk(ap_clk);
    imgInTmp2_channel_U->reset(ap_rst_n_inv);
    imgInTmp2_channel_U->if_read_ce(imgInTmp2_channel_U_ap_dummy_ce);
    imgInTmp2_channel_U->if_write_ce(imgInTmp2_channel_U_ap_dummy_ce);
    imgInTmp2_channel_U->if_din(imgInTmp2_channel_din);
    imgInTmp2_channel_U->if_full_n(imgInTmp2_channel_full_n);
    imgInTmp2_channel_U->if_write(imgInTmp2_channel_write);
    imgInTmp2_channel_U->if_dout(imgInTmp2_channel_dout);
    imgInTmp2_channel_U->if_empty_n(imgInTmp2_channel_empty_n);
    imgInTmp2_channel_U->if_read(imgInTmp2_channel_read);
    fft_config2_data_V_U = new FIFO_pyrconstuct_top_fft_config2_data_V("fft_config2_data_V_U");
    fft_config2_data_V_U->clk(ap_clk);
    fft_config2_data_V_U->reset(ap_rst_n_inv);
    fft_config2_data_V_U->if_read_ce(fft_config2_data_V_U_ap_dummy_ce);
    fft_config2_data_V_U->if_write_ce(fft_config2_data_V_U_ap_dummy_ce);
    fft_config2_data_V_U->if_din(fft_config2_data_V_din);
    fft_config2_data_V_U->if_full_n(fft_config2_data_V_full_n);
    fft_config2_data_V_U->if_write(fft_config2_data_V_write);
    fft_config2_data_V_U->if_dout(fft_config2_data_V_dout);
    fft_config2_data_V_U->if_empty_n(fft_config2_data_V_empty_n);
    fft_config2_data_V_U->if_read(fft_config2_data_V_read);
    ifftPyrOut_channel_U = new FIFO_pyrconstuct_top_ifftPyrOut_channel("ifftPyrOut_channel_U");
    ifftPyrOut_channel_U->clk(ap_clk);
    ifftPyrOut_channel_U->reset(ap_rst_n_inv);
    ifftPyrOut_channel_U->if_read_ce(ifftPyrOut_channel_U_ap_dummy_ce);
    ifftPyrOut_channel_U->if_write_ce(ifftPyrOut_channel_U_ap_dummy_ce);
    ifftPyrOut_channel_U->if_din(ifftPyrOut_channel_din);
    ifftPyrOut_channel_U->if_full_n(ifftPyrOut_channel_full_n);
    ifftPyrOut_channel_U->if_write(ifftPyrOut_channel_write);
    ifftPyrOut_channel_U->if_dout(ifftPyrOut_channel_dout);
    ifftPyrOut_channel_U->if_empty_n(ifftPyrOut_channel_empty_n);
    ifftPyrOut_channel_U->if_read(ifftPyrOut_channel_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_ap_done );
    sensitive << ( ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status );

    SC_METHOD(thread_ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_ap_done );
    sensitive << ( ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( pyrconstuct_top_Block_codeRepl26_proc_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Loop_1_proc_U0_ap_idle );
    sensitive << ( fft_config1_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Loop_4_proc_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Block_proc_U0_ap_idle );
    sensitive << ( fft_config2_U0_ap_idle );
    sensitive << ( pyrconstuct_top_Loop_5_proc_U0_ap_idle );
    sensitive << ( imgOutTmpBlockRam_M_real_V_t_empty_n );
    sensitive << ( imgOutTmpBlockRam_M_imag_V_t_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( pyrconstuct_top_Loop_5_proc_U0_ap_done );

    SC_METHOD(thread_ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status );
    sensitive << ( ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status );

    SC_METHOD(thread_ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status );
    sensitive << ( ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( pyrconstuct_top_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_fftPyrOut_M_imag_V_U_ap_dummy_ce);

    SC_METHOD(thread_fftPyrOut_M_imag_V_din);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_din );

    SC_METHOD(thread_fftPyrOut_M_imag_V_read);
    sensitive << ( pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_read );

    SC_METHOD(thread_fftPyrOut_M_imag_V_write);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_write );

    SC_METHOD(thread_fftPyrOut_M_real_V_U_ap_dummy_ce);

    SC_METHOD(thread_fftPyrOut_M_real_V_din);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_din );

    SC_METHOD(thread_fftPyrOut_M_real_V_read);
    sensitive << ( pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_read );

    SC_METHOD(thread_fftPyrOut_M_real_V_write);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_write );

    SC_METHOD(thread_fft_config1_U0_ap_ce);

    SC_METHOD(thread_fft_config1_U0_ap_continue);

    SC_METHOD(thread_fft_config1_U0_config_ch_data_V_dout);
    sensitive << ( fft_config_data_V_channel_dout );

    SC_METHOD(thread_fft_config1_U0_config_ch_data_V_empty_n);
    sensitive << ( fft_config_data_V_channel_empty_n );

    SC_METHOD(thread_fft_config1_U0_status_data_V_full_n);

    SC_METHOD(thread_fft_config1_U0_xk_full_n);
    sensitive << ( imgOutTmpFFTStream_channel_full_n );

    SC_METHOD(thread_fft_config1_U0_xn_dout);
    sensitive << ( imgInTmp_channel_dout );

    SC_METHOD(thread_fft_config1_U0_xn_empty_n);
    sensitive << ( imgInTmp_channel_empty_n );

    SC_METHOD(thread_fft_config2_U0_ap_ce);

    SC_METHOD(thread_fft_config2_U0_ap_continue);

    SC_METHOD(thread_fft_config2_U0_config_ch_data_V_dout);
    sensitive << ( fft_config2_data_V_dout );

    SC_METHOD(thread_fft_config2_U0_config_ch_data_V_empty_n);
    sensitive << ( fft_config2_data_V_empty_n );

    SC_METHOD(thread_fft_config2_U0_status_data_V_full_n);

    SC_METHOD(thread_fft_config2_U0_xk_full_n);
    sensitive << ( ifftPyrOut_channel_full_n );

    SC_METHOD(thread_fft_config2_U0_xn_dout);
    sensitive << ( imgInTmp2_channel_dout );

    SC_METHOD(thread_fft_config2_U0_xn_empty_n);
    sensitive << ( imgInTmp2_channel_empty_n );

    SC_METHOD(thread_fft_config2_data_V_U_ap_dummy_ce);

    SC_METHOD(thread_fft_config2_data_V_din);
    sensitive << ( pyrconstuct_top_Block_proc_U0_fft_config2_data_V_din );

    SC_METHOD(thread_fft_config2_data_V_read);
    sensitive << ( fft_config2_U0_config_ch_data_V_read );

    SC_METHOD(thread_fft_config2_data_V_write);
    sensitive << ( pyrconstuct_top_Block_proc_U0_fft_config2_data_V_write );

    SC_METHOD(thread_fft_config_data_V_channel_U_ap_dummy_ce);

    SC_METHOD(thread_fft_config_data_V_channel_din);
    sensitive << ( pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_din );

    SC_METHOD(thread_fft_config_data_V_channel_read);
    sensitive << ( fft_config1_U0_config_ch_data_V_read );

    SC_METHOD(thread_fft_config_data_V_channel_write);
    sensitive << ( pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_write );

    SC_METHOD(thread_ifftPyrOut_channel_U_ap_dummy_ce);

    SC_METHOD(thread_ifftPyrOut_channel_din);
    sensitive << ( fft_config2_U0_xk_din );

    SC_METHOD(thread_ifftPyrOut_channel_read);
    sensitive << ( pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_read );

    SC_METHOD(thread_ifftPyrOut_channel_write);
    sensitive << ( fft_config2_U0_xk_write );

    SC_METHOD(thread_imgInTmp2_channel_U_ap_dummy_ce);

    SC_METHOD(thread_imgInTmp2_channel_din);
    sensitive << ( pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_din );

    SC_METHOD(thread_imgInTmp2_channel_read);
    sensitive << ( fft_config2_U0_xn_read );

    SC_METHOD(thread_imgInTmp2_channel_write);
    sensitive << ( pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_write );

    SC_METHOD(thread_imgInTmp_channel_U_ap_dummy_ce);

    SC_METHOD(thread_imgInTmp_channel_din);
    sensitive << ( pyrconstuct_top_Loop_1_proc_U0_imgInTmp_din );

    SC_METHOD(thread_imgInTmp_channel_read);
    sensitive << ( fft_config1_U0_xn_read );

    SC_METHOD(thread_imgInTmp_channel_write);
    sensitive << ( pyrconstuct_top_Loop_1_proc_U0_imgInTmp_write );

    SC_METHOD(thread_imgIn_TREADY);
    sensitive << ( pyrconstuct_top_Loop_1_proc_U0_imgIn_TREADY );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce);

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_i_address0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_address0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_i_ce0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_i_d0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_d0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_i_we0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_we0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_i_write);
    sensitive << ( ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_t_address0);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_address0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_t_ce0);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_t_d0);

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_t_read);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_ap_ready );

    SC_METHOD(thread_imgOutTmpBlockRam_M_imag_V_t_we0);

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce);

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_i_address0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_address0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_i_ce0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_ce0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_i_d0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_d0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_i_we0);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_we0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_i_write);
    sensitive << ( ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_t_address0);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_address0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_t_ce0);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_ce0 );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_t_d0);

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_t_read);
    sensitive << ( pyrconstuct_top_Loop_3_proc_U0_ap_ready );

    SC_METHOD(thread_imgOutTmpBlockRam_M_real_V_t_we0);

    SC_METHOD(thread_imgOutTmpFFTStream_channel_U_ap_dummy_ce);

    SC_METHOD(thread_imgOutTmpFFTStream_channel_din);
    sensitive << ( fft_config1_U0_xk_din );

    SC_METHOD(thread_imgOutTmpFFTStream_channel_read);
    sensitive << ( pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_read );

    SC_METHOD(thread_imgOutTmpFFTStream_channel_write);
    sensitive << ( fft_config1_U0_xk_write );

    SC_METHOD(thread_pyrFilOut_V_TDATA);
    sensitive << ( pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TDATA );

    SC_METHOD(thread_pyrFilOut_V_TVALID);
    sensitive << ( pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TVALID );

    SC_METHOD(thread_pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue);

    SC_METHOD(thread_pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n);
    sensitive << ( fft_config_data_V_channel_full_n );

    SC_METHOD(thread_pyrconstuct_top_Block_proc_U0_ap_continue);

    SC_METHOD(thread_pyrconstuct_top_Block_proc_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n);
    sensitive << ( fft_config2_data_V_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_1_proc_U0_ap_continue);

    SC_METHOD(thread_pyrconstuct_top_Loop_1_proc_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n);
    sensitive << ( imgInTmp_channel_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA);
    sensitive << ( imgIn_TDATA );

    SC_METHOD(thread_pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID);
    sensitive << ( imgIn_TVALID );

    SC_METHOD(thread_pyrconstuct_top_Loop_2_proc_U0_ap_continue);
    sensitive << ( ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status );
    sensitive << ( ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status );

    SC_METHOD(thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status);
    sensitive << ( imgOutTmpBlockRam_M_imag_V_i_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status);
    sensitive << ( imgOutTmpBlockRam_M_real_V_i_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout);
    sensitive << ( imgOutTmpFFTStream_channel_dout );

    SC_METHOD(thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n);
    sensitive << ( imgOutTmpFFTStream_channel_empty_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_ap_continue);

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_ap_start);
    sensitive << ( imgOutTmpBlockRam_M_real_V_t_empty_n );
    sensitive << ( imgOutTmpBlockRam_M_imag_V_t_empty_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n);
    sensitive << ( fftPyrOut_M_imag_V_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n);
    sensitive << ( fftPyrOut_M_real_V_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0);
    sensitive << ( imgOutTmpBlockRam_M_imag_V_t_q0 );

    SC_METHOD(thread_pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0);
    sensitive << ( imgOutTmpBlockRam_M_real_V_t_q0 );

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_ap_continue);

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout);
    sensitive << ( fftPyrOut_M_imag_V_dout );

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n);
    sensitive << ( fftPyrOut_M_imag_V_empty_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout);
    sensitive << ( fftPyrOut_M_real_V_dout );

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n);
    sensitive << ( fftPyrOut_M_real_V_empty_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n);
    sensitive << ( imgInTmp2_channel_full_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_5_proc_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout);
    sensitive << ( ifftPyrOut_channel_dout );

    SC_METHOD(thread_pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n);
    sensitive << ( ifftPyrOut_channel_empty_n );

    SC_METHOD(thread_pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY);
    sensitive << ( pyrFilOut_V_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    fft_config1_U0_ap_start = SC_LOGIC_0;
    pyrconstuct_top_Loop_2_proc_U0_ap_start = SC_LOGIC_0;
    ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = SC_LOGIC_0;
    ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = SC_LOGIC_0;
    pyrconstuct_top_Loop_4_proc_U0_ap_start = SC_LOGIC_0;
    fft_config2_U0_ap_start = SC_LOGIC_0;
    pyrconstuct_top_Loop_5_proc_U0_ap_start = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_fft_config1_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Block_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_fft_config2_U0 = SC_LOGIC_0;
    ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pyrconstuct_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, imgIn_TDATA, "(port)imgIn_TDATA");
    sc_trace(mVcdFile, pyrFilOut_V_TDATA, "(port)pyrFilOut_V_TDATA");
    sc_trace(mVcdFile, nL, "(port)nL");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, imgIn_TVALID, "(port)imgIn_TVALID");
    sc_trace(mVcdFile, imgIn_TREADY, "(port)imgIn_TREADY");
    sc_trace(mVcdFile, pyrFilOut_V_TVALID, "(port)pyrFilOut_V_TVALID");
    sc_trace(mVcdFile, pyrFilOut_V_TREADY, "(port)pyrFilOut_V_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_address0, "imgOutTmpBlockRam_M_real_V_i_address0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_ce0, "imgOutTmpBlockRam_M_real_V_i_ce0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_we0, "imgOutTmpBlockRam_M_real_V_i_we0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_d0, "imgOutTmpBlockRam_M_real_V_i_d0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_q0, "imgOutTmpBlockRam_M_real_V_i_q0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_address0, "imgOutTmpBlockRam_M_real_V_t_address0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_ce0, "imgOutTmpBlockRam_M_real_V_t_ce0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_we0, "imgOutTmpBlockRam_M_real_V_t_we0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_d0, "imgOutTmpBlockRam_M_real_V_t_d0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_q0, "imgOutTmpBlockRam_M_real_V_t_q0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce, "imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_address0, "imgOutTmpBlockRam_M_imag_V_i_address0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_ce0, "imgOutTmpBlockRam_M_imag_V_i_ce0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_we0, "imgOutTmpBlockRam_M_imag_V_i_we0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_d0, "imgOutTmpBlockRam_M_imag_V_i_d0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_q0, "imgOutTmpBlockRam_M_imag_V_i_q0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_address0, "imgOutTmpBlockRam_M_imag_V_t_address0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_ce0, "imgOutTmpBlockRam_M_imag_V_t_ce0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_we0, "imgOutTmpBlockRam_M_imag_V_t_we0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_d0, "imgOutTmpBlockRam_M_imag_V_t_d0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_q0, "imgOutTmpBlockRam_M_imag_V_t_q0");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce, "imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start, "pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_done, "pyrconstuct_top_Block_codeRepl26_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue, "pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_idle, "pyrconstuct_top_Block_codeRepl26_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_ready, "pyrconstuct_top_Block_codeRepl26_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_din, "pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_din");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n, "pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_write, "pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_write");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_ap_start, "pyrconstuct_top_Loop_1_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_ap_done, "pyrconstuct_top_Loop_1_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_ap_continue, "pyrconstuct_top_Loop_1_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_ap_idle, "pyrconstuct_top_Loop_1_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_ap_ready, "pyrconstuct_top_Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA, "pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID, "pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgIn_TREADY, "pyrconstuct_top_Loop_1_proc_U0_imgIn_TREADY");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgInTmp_din, "pyrconstuct_top_Loop_1_proc_U0_imgInTmp_din");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n, "pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_1_proc_U0_imgInTmp_write, "pyrconstuct_top_Loop_1_proc_U0_imgInTmp_write");
    sc_trace(mVcdFile, fft_config1_U0_ap_start, "fft_config1_U0_ap_start");
    sc_trace(mVcdFile, fft_config1_U0_ap_ce, "fft_config1_U0_ap_ce");
    sc_trace(mVcdFile, fft_config1_U0_ap_done, "fft_config1_U0_ap_done");
    sc_trace(mVcdFile, fft_config1_U0_ap_idle, "fft_config1_U0_ap_idle");
    sc_trace(mVcdFile, fft_config1_U0_ap_ready, "fft_config1_U0_ap_ready");
    sc_trace(mVcdFile, fft_config1_U0_xn_dout, "fft_config1_U0_xn_dout");
    sc_trace(mVcdFile, fft_config1_U0_xn_empty_n, "fft_config1_U0_xn_empty_n");
    sc_trace(mVcdFile, fft_config1_U0_xn_read, "fft_config1_U0_xn_read");
    sc_trace(mVcdFile, fft_config1_U0_xk_din, "fft_config1_U0_xk_din");
    sc_trace(mVcdFile, fft_config1_U0_xk_full_n, "fft_config1_U0_xk_full_n");
    sc_trace(mVcdFile, fft_config1_U0_xk_write, "fft_config1_U0_xk_write");
    sc_trace(mVcdFile, fft_config1_U0_status_data_V_din, "fft_config1_U0_status_data_V_din");
    sc_trace(mVcdFile, fft_config1_U0_status_data_V_full_n, "fft_config1_U0_status_data_V_full_n");
    sc_trace(mVcdFile, fft_config1_U0_status_data_V_write, "fft_config1_U0_status_data_V_write");
    sc_trace(mVcdFile, fft_config1_U0_config_ch_data_V_dout, "fft_config1_U0_config_ch_data_V_dout");
    sc_trace(mVcdFile, fft_config1_U0_config_ch_data_V_empty_n, "fft_config1_U0_config_ch_data_V_empty_n");
    sc_trace(mVcdFile, fft_config1_U0_config_ch_data_V_read, "fft_config1_U0_config_ch_data_V_read");
    sc_trace(mVcdFile, fft_config1_U0_ap_continue, "fft_config1_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_ap_start, "pyrconstuct_top_Loop_2_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_ap_done, "pyrconstuct_top_Loop_2_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_ap_continue, "pyrconstuct_top_Loop_2_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_ap_idle, "pyrconstuct_top_Loop_2_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_ap_ready, "pyrconstuct_top_Loop_2_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_read, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_read");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_address0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_address0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_ce0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_ce0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_we0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_we0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_d0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_d0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_address0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_address0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_we0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_we0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_d0, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_d0");
    sc_trace(mVcdFile, ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V, "ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status");
    sc_trace(mVcdFile, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status, "ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status");
    sc_trace(mVcdFile, ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status, "ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status");
    sc_trace(mVcdFile, ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V, "ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status, "pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status");
    sc_trace(mVcdFile, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status, "ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status");
    sc_trace(mVcdFile, ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status, "ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_ap_start, "pyrconstuct_top_Loop_3_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_ap_done, "pyrconstuct_top_Loop_3_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_ap_continue, "pyrconstuct_top_Loop_3_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_ap_idle, "pyrconstuct_top_Loop_3_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_ap_ready, "pyrconstuct_top_Loop_3_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_address0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_address0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_ce0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_ce0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_address0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_address0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0, "pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_din, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_din");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_write, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_write");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_din, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_din");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_write, "pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_write");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_ap_start, "pyrconstuct_top_Loop_4_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_ap_done, "pyrconstuct_top_Loop_4_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_ap_continue, "pyrconstuct_top_Loop_4_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_ap_idle, "pyrconstuct_top_Loop_4_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_ap_ready, "pyrconstuct_top_Loop_4_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_read, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_read");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_read, "pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_read");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_din, "pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_din");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n, "pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_write, "pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_write");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_ap_start, "pyrconstuct_top_Block_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_ap_done, "pyrconstuct_top_Block_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_ap_continue, "pyrconstuct_top_Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_ap_idle, "pyrconstuct_top_Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_ap_ready, "pyrconstuct_top_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_fft_config2_data_V_din, "pyrconstuct_top_Block_proc_U0_fft_config2_data_V_din");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n, "pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n");
    sc_trace(mVcdFile, pyrconstuct_top_Block_proc_U0_fft_config2_data_V_write, "pyrconstuct_top_Block_proc_U0_fft_config2_data_V_write");
    sc_trace(mVcdFile, fft_config2_U0_ap_start, "fft_config2_U0_ap_start");
    sc_trace(mVcdFile, fft_config2_U0_ap_ce, "fft_config2_U0_ap_ce");
    sc_trace(mVcdFile, fft_config2_U0_ap_done, "fft_config2_U0_ap_done");
    sc_trace(mVcdFile, fft_config2_U0_ap_idle, "fft_config2_U0_ap_idle");
    sc_trace(mVcdFile, fft_config2_U0_ap_ready, "fft_config2_U0_ap_ready");
    sc_trace(mVcdFile, fft_config2_U0_xn_dout, "fft_config2_U0_xn_dout");
    sc_trace(mVcdFile, fft_config2_U0_xn_empty_n, "fft_config2_U0_xn_empty_n");
    sc_trace(mVcdFile, fft_config2_U0_xn_read, "fft_config2_U0_xn_read");
    sc_trace(mVcdFile, fft_config2_U0_xk_din, "fft_config2_U0_xk_din");
    sc_trace(mVcdFile, fft_config2_U0_xk_full_n, "fft_config2_U0_xk_full_n");
    sc_trace(mVcdFile, fft_config2_U0_xk_write, "fft_config2_U0_xk_write");
    sc_trace(mVcdFile, fft_config2_U0_status_data_V_din, "fft_config2_U0_status_data_V_din");
    sc_trace(mVcdFile, fft_config2_U0_status_data_V_full_n, "fft_config2_U0_status_data_V_full_n");
    sc_trace(mVcdFile, fft_config2_U0_status_data_V_write, "fft_config2_U0_status_data_V_write");
    sc_trace(mVcdFile, fft_config2_U0_config_ch_data_V_dout, "fft_config2_U0_config_ch_data_V_dout");
    sc_trace(mVcdFile, fft_config2_U0_config_ch_data_V_empty_n, "fft_config2_U0_config_ch_data_V_empty_n");
    sc_trace(mVcdFile, fft_config2_U0_config_ch_data_V_read, "fft_config2_U0_config_ch_data_V_read");
    sc_trace(mVcdFile, fft_config2_U0_ap_continue, "fft_config2_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ap_start, "pyrconstuct_top_Loop_5_proc_U0_ap_start");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ap_done, "pyrconstuct_top_Loop_5_proc_U0_ap_done");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ap_continue, "pyrconstuct_top_Loop_5_proc_U0_ap_continue");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ap_idle, "pyrconstuct_top_Loop_5_proc_U0_ap_idle");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ap_ready, "pyrconstuct_top_Loop_5_proc_U0_ap_ready");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout, "pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n, "pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_read, "pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_read");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TDATA, "pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TDATA");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TVALID, "pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TVALID");
    sc_trace(mVcdFile, pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY, "pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_full_n, "imgOutTmpBlockRam_M_real_V_i_full_n");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_i_write, "imgOutTmpBlockRam_M_real_V_i_write");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_empty_n, "imgOutTmpBlockRam_M_real_V_t_empty_n");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_real_V_t_read, "imgOutTmpBlockRam_M_real_V_t_read");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_full_n, "imgOutTmpBlockRam_M_imag_V_i_full_n");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_i_write, "imgOutTmpBlockRam_M_imag_V_i_write");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_empty_n, "imgOutTmpBlockRam_M_imag_V_t_empty_n");
    sc_trace(mVcdFile, imgOutTmpBlockRam_M_imag_V_t_read, "imgOutTmpBlockRam_M_imag_V_t_read");
    sc_trace(mVcdFile, fft_config_data_V_channel_U_ap_dummy_ce, "fft_config_data_V_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, fft_config_data_V_channel_din, "fft_config_data_V_channel_din");
    sc_trace(mVcdFile, fft_config_data_V_channel_full_n, "fft_config_data_V_channel_full_n");
    sc_trace(mVcdFile, fft_config_data_V_channel_write, "fft_config_data_V_channel_write");
    sc_trace(mVcdFile, fft_config_data_V_channel_dout, "fft_config_data_V_channel_dout");
    sc_trace(mVcdFile, fft_config_data_V_channel_empty_n, "fft_config_data_V_channel_empty_n");
    sc_trace(mVcdFile, fft_config_data_V_channel_read, "fft_config_data_V_channel_read");
    sc_trace(mVcdFile, imgInTmp_channel_U_ap_dummy_ce, "imgInTmp_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, imgInTmp_channel_din, "imgInTmp_channel_din");
    sc_trace(mVcdFile, imgInTmp_channel_full_n, "imgInTmp_channel_full_n");
    sc_trace(mVcdFile, imgInTmp_channel_write, "imgInTmp_channel_write");
    sc_trace(mVcdFile, imgInTmp_channel_dout, "imgInTmp_channel_dout");
    sc_trace(mVcdFile, imgInTmp_channel_empty_n, "imgInTmp_channel_empty_n");
    sc_trace(mVcdFile, imgInTmp_channel_read, "imgInTmp_channel_read");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_U_ap_dummy_ce, "imgOutTmpFFTStream_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_din, "imgOutTmpFFTStream_channel_din");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_full_n, "imgOutTmpFFTStream_channel_full_n");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_write, "imgOutTmpFFTStream_channel_write");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_dout, "imgOutTmpFFTStream_channel_dout");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_empty_n, "imgOutTmpFFTStream_channel_empty_n");
    sc_trace(mVcdFile, imgOutTmpFFTStream_channel_read, "imgOutTmpFFTStream_channel_read");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_U_ap_dummy_ce, "fftPyrOut_M_real_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_din, "fftPyrOut_M_real_V_din");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_full_n, "fftPyrOut_M_real_V_full_n");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_write, "fftPyrOut_M_real_V_write");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_dout, "fftPyrOut_M_real_V_dout");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_empty_n, "fftPyrOut_M_real_V_empty_n");
    sc_trace(mVcdFile, fftPyrOut_M_real_V_read, "fftPyrOut_M_real_V_read");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_U_ap_dummy_ce, "fftPyrOut_M_imag_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_din, "fftPyrOut_M_imag_V_din");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_full_n, "fftPyrOut_M_imag_V_full_n");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_write, "fftPyrOut_M_imag_V_write");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_dout, "fftPyrOut_M_imag_V_dout");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_empty_n, "fftPyrOut_M_imag_V_empty_n");
    sc_trace(mVcdFile, fftPyrOut_M_imag_V_read, "fftPyrOut_M_imag_V_read");
    sc_trace(mVcdFile, imgInTmp2_channel_U_ap_dummy_ce, "imgInTmp2_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, imgInTmp2_channel_din, "imgInTmp2_channel_din");
    sc_trace(mVcdFile, imgInTmp2_channel_full_n, "imgInTmp2_channel_full_n");
    sc_trace(mVcdFile, imgInTmp2_channel_write, "imgInTmp2_channel_write");
    sc_trace(mVcdFile, imgInTmp2_channel_dout, "imgInTmp2_channel_dout");
    sc_trace(mVcdFile, imgInTmp2_channel_empty_n, "imgInTmp2_channel_empty_n");
    sc_trace(mVcdFile, imgInTmp2_channel_read, "imgInTmp2_channel_read");
    sc_trace(mVcdFile, fft_config2_data_V_U_ap_dummy_ce, "fft_config2_data_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, fft_config2_data_V_din, "fft_config2_data_V_din");
    sc_trace(mVcdFile, fft_config2_data_V_full_n, "fft_config2_data_V_full_n");
    sc_trace(mVcdFile, fft_config2_data_V_write, "fft_config2_data_V_write");
    sc_trace(mVcdFile, fft_config2_data_V_dout, "fft_config2_data_V_dout");
    sc_trace(mVcdFile, fft_config2_data_V_empty_n, "fft_config2_data_V_empty_n");
    sc_trace(mVcdFile, fft_config2_data_V_read, "fft_config2_data_V_read");
    sc_trace(mVcdFile, ifftPyrOut_channel_U_ap_dummy_ce, "ifftPyrOut_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, ifftPyrOut_channel_din, "ifftPyrOut_channel_din");
    sc_trace(mVcdFile, ifftPyrOut_channel_full_n, "ifftPyrOut_channel_full_n");
    sc_trace(mVcdFile, ifftPyrOut_channel_write, "ifftPyrOut_channel_write");
    sc_trace(mVcdFile, ifftPyrOut_channel_dout, "ifftPyrOut_channel_dout");
    sc_trace(mVcdFile, ifftPyrOut_channel_empty_n, "ifftPyrOut_channel_empty_n");
    sc_trace(mVcdFile, ifftPyrOut_channel_read, "ifftPyrOut_channel_read");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0, "ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0, "ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0");
    sc_trace(mVcdFile, ap_reg_procdone_fft_config1_U0, "ap_reg_procdone_fft_config1_U0");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0, "ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0, "ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0, "ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Block_proc_U0, "ap_reg_procdone_pyrconstuct_top_Block_proc_U0");
    sc_trace(mVcdFile, ap_reg_procdone_fft_config2_U0, "ap_reg_procdone_fft_config2_U0");
    sc_trace(mVcdFile, ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0, "ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
    mHdltvinHandle.open("pyrconstuct_top.hdltvin.dat");
    mHdltvoutHandle.open("pyrconstuct_top.hdltvout.dat");
}

pyrconstuct_top::~pyrconstuct_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete imgOutTmpBlockRam_M_real_V_U;
    delete imgOutTmpBlockRam_M_imag_V_U;
    delete pyrconstuct_top_Block_codeRepl26_proc_U0;
    delete pyrconstuct_top_Loop_1_proc_U0;
    delete fft_config1_U0;
    delete pyrconstuct_top_Loop_2_proc_U0;
    delete pyrconstuct_top_Loop_3_proc_U0;
    delete pyrconstuct_top_Loop_4_proc_U0;
    delete pyrconstuct_top_Block_proc_U0;
    delete fft_config2_U0;
    delete pyrconstuct_top_Loop_5_proc_U0;
    delete fft_config_data_V_channel_U;
    delete imgInTmp_channel_U;
    delete imgOutTmpFFTStream_channel_U;
    delete fftPyrOut_M_real_V_U;
    delete fftPyrOut_M_imag_V_U;
    delete imgInTmp2_channel_U;
    delete fft_config2_data_V_U;
    delete ifftPyrOut_channel_U;
}

void pyrconstuct_top::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_fft_config1_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_fft_config1_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, fft_config1_U0_ap_done.read())) {
            ap_reg_procdone_fft_config1_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_fft_config2_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_fft_config2_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, fft_config2_U0_ap_done.read())) {
            ap_reg_procdone_fft_config2_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Block_codeRepl26_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Block_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Block_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Block_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Block_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_1_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_1_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_2_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_3_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_3_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_4_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_4_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_5_proc_U0_ap_done.read())) {
            ap_reg_procdone_pyrconstuct_top_Loop_5_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_done.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_continue.read()))) {
            ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_done.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status.read()))) {
            ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_done.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_continue.read()))) {
            ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_done.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status.read()))) {
            ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        fft_config1_U0_ap_start = ap_const_logic_0;
    } else {
        fft_config1_U0_ap_start = ap_const_logic_1;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        fft_config2_U0_ap_start = ap_const_logic_0;
    } else {
        fft_config2_U0_ap_start = ap_const_logic_1;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        pyrconstuct_top_Loop_2_proc_U0_ap_start = ap_const_logic_0;
    } else {
        pyrconstuct_top_Loop_2_proc_U0_ap_start = ap_const_logic_1;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        pyrconstuct_top_Loop_4_proc_U0_ap_start = ap_const_logic_0;
    } else {
        pyrconstuct_top_Loop_4_proc_U0_ap_start = ap_const_logic_1;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        pyrconstuct_top_Loop_5_proc_U0_ap_start = ap_const_logic_0;
    } else {
        pyrconstuct_top_Loop_5_proc_U0_ap_start = ap_const_logic_1;
    }
}

void pyrconstuct_top::thread_ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status.read())) {
        ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V = ap_const_logic_0;
    } else {
        ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V = pyrconstuct_top_Loop_2_proc_U0_ap_done.read();
    }
}

void pyrconstuct_top::thread_ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status.read())) {
        ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V = ap_const_logic_0;
    } else {
        ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V = pyrconstuct_top_Loop_2_proc_U0_ap_done.read();
    }
}

void pyrconstuct_top::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void pyrconstuct_top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Block_codeRepl26_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_1_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, fft_config1_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_2_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_3_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_4_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Block_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, fft_config2_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_5_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, imgOutTmpBlockRam_M_real_V_t_empty_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, imgOutTmpBlockRam_M_imag_V_t_empty_n.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pyrconstuct_top::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void pyrconstuct_top::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void pyrconstuct_top::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, pyrconstuct_top_Loop_5_proc_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void pyrconstuct_top::thread_ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status.read())) {
        ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status.read();
    } else {
        ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = ap_const_logic_1;
    }
}

void pyrconstuct_top::thread_ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status.read())) {
        ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status.read();
    } else {
        ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = ap_const_logic_1;
    }
}

void pyrconstuct_top::thread_ap_sig_top_allready() {
    ap_sig_top_allready = pyrconstuct_top_Loop_1_proc_U0_ap_ready.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_imag_V_U_ap_dummy_ce() {
    fftPyrOut_M_imag_V_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fftPyrOut_M_imag_V_din() {
    fftPyrOut_M_imag_V_din = pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_din.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_imag_V_read() {
    fftPyrOut_M_imag_V_read = pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_read.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_imag_V_write() {
    fftPyrOut_M_imag_V_write = pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_write.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_real_V_U_ap_dummy_ce() {
    fftPyrOut_M_real_V_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fftPyrOut_M_real_V_din() {
    fftPyrOut_M_real_V_din = pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_din.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_real_V_read() {
    fftPyrOut_M_real_V_read = pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_read.read();
}

void pyrconstuct_top::thread_fftPyrOut_M_real_V_write() {
    fftPyrOut_M_real_V_write = pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_write.read();
}

void pyrconstuct_top::thread_fft_config1_U0_ap_ce() {
    fft_config1_U0_ap_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config1_U0_ap_continue() {
    fft_config1_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config1_U0_config_ch_data_V_dout() {
    fft_config1_U0_config_ch_data_V_dout = fft_config_data_V_channel_dout.read();
}

void pyrconstuct_top::thread_fft_config1_U0_config_ch_data_V_empty_n() {
    fft_config1_U0_config_ch_data_V_empty_n = fft_config_data_V_channel_empty_n.read();
}

void pyrconstuct_top::thread_fft_config1_U0_status_data_V_full_n() {
    fft_config1_U0_status_data_V_full_n = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config1_U0_xk_full_n() {
    fft_config1_U0_xk_full_n = imgOutTmpFFTStream_channel_full_n.read();
}

void pyrconstuct_top::thread_fft_config1_U0_xn_dout() {
    fft_config1_U0_xn_dout = imgInTmp_channel_dout.read();
}

void pyrconstuct_top::thread_fft_config1_U0_xn_empty_n() {
    fft_config1_U0_xn_empty_n = imgInTmp_channel_empty_n.read();
}

void pyrconstuct_top::thread_fft_config2_U0_ap_ce() {
    fft_config2_U0_ap_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config2_U0_ap_continue() {
    fft_config2_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config2_U0_config_ch_data_V_dout() {
    fft_config2_U0_config_ch_data_V_dout = fft_config2_data_V_dout.read();
}

void pyrconstuct_top::thread_fft_config2_U0_config_ch_data_V_empty_n() {
    fft_config2_U0_config_ch_data_V_empty_n = fft_config2_data_V_empty_n.read();
}

void pyrconstuct_top::thread_fft_config2_U0_status_data_V_full_n() {
    fft_config2_U0_status_data_V_full_n = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config2_U0_xk_full_n() {
    fft_config2_U0_xk_full_n = ifftPyrOut_channel_full_n.read();
}

void pyrconstuct_top::thread_fft_config2_U0_xn_dout() {
    fft_config2_U0_xn_dout = imgInTmp2_channel_dout.read();
}

void pyrconstuct_top::thread_fft_config2_U0_xn_empty_n() {
    fft_config2_U0_xn_empty_n = imgInTmp2_channel_empty_n.read();
}

void pyrconstuct_top::thread_fft_config2_data_V_U_ap_dummy_ce() {
    fft_config2_data_V_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config2_data_V_din() {
    fft_config2_data_V_din = pyrconstuct_top_Block_proc_U0_fft_config2_data_V_din.read();
}

void pyrconstuct_top::thread_fft_config2_data_V_read() {
    fft_config2_data_V_read = fft_config2_U0_config_ch_data_V_read.read();
}

void pyrconstuct_top::thread_fft_config2_data_V_write() {
    fft_config2_data_V_write = pyrconstuct_top_Block_proc_U0_fft_config2_data_V_write.read();
}

void pyrconstuct_top::thread_fft_config_data_V_channel_U_ap_dummy_ce() {
    fft_config_data_V_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_fft_config_data_V_channel_din() {
    fft_config_data_V_channel_din = pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_din.read();
}

void pyrconstuct_top::thread_fft_config_data_V_channel_read() {
    fft_config_data_V_channel_read = fft_config1_U0_config_ch_data_V_read.read();
}

void pyrconstuct_top::thread_fft_config_data_V_channel_write() {
    fft_config_data_V_channel_write = pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_write.read();
}

void pyrconstuct_top::thread_ifftPyrOut_channel_U_ap_dummy_ce() {
    ifftPyrOut_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_ifftPyrOut_channel_din() {
    ifftPyrOut_channel_din = fft_config2_U0_xk_din.read();
}

void pyrconstuct_top::thread_ifftPyrOut_channel_read() {
    ifftPyrOut_channel_read = pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_read.read();
}

void pyrconstuct_top::thread_ifftPyrOut_channel_write() {
    ifftPyrOut_channel_write = fft_config2_U0_xk_write.read();
}

void pyrconstuct_top::thread_imgInTmp2_channel_U_ap_dummy_ce() {
    imgInTmp2_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_imgInTmp2_channel_din() {
    imgInTmp2_channel_din = pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_din.read();
}

void pyrconstuct_top::thread_imgInTmp2_channel_read() {
    imgInTmp2_channel_read = fft_config2_U0_xn_read.read();
}

void pyrconstuct_top::thread_imgInTmp2_channel_write() {
    imgInTmp2_channel_write = pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_write.read();
}

void pyrconstuct_top::thread_imgInTmp_channel_U_ap_dummy_ce() {
    imgInTmp_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_imgInTmp_channel_din() {
    imgInTmp_channel_din = pyrconstuct_top_Loop_1_proc_U0_imgInTmp_din.read();
}

void pyrconstuct_top::thread_imgInTmp_channel_read() {
    imgInTmp_channel_read = fft_config1_U0_xn_read.read();
}

void pyrconstuct_top::thread_imgInTmp_channel_write() {
    imgInTmp_channel_write = pyrconstuct_top_Loop_1_proc_U0_imgInTmp_write.read();
}

void pyrconstuct_top::thread_imgIn_TREADY() {
    imgIn_TREADY = pyrconstuct_top_Loop_1_proc_U0_imgIn_TREADY.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce() {
    imgOutTmpBlockRam_M_imag_V_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_i_address0() {
    imgOutTmpBlockRam_M_imag_V_i_address0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_address0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_i_ce0() {
    imgOutTmpBlockRam_M_imag_V_i_ce0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_i_d0() {
    imgOutTmpBlockRam_M_imag_V_i_d0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_d0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_i_we0() {
    imgOutTmpBlockRam_M_imag_V_i_we0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_we0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_i_write() {
    imgOutTmpBlockRam_M_imag_V_i_write = ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_t_address0() {
    imgOutTmpBlockRam_M_imag_V_t_address0 = pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_address0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_t_ce0() {
    imgOutTmpBlockRam_M_imag_V_t_ce0 = pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_ce0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_t_d0() {
    imgOutTmpBlockRam_M_imag_V_t_d0 = ap_const_lv24_0;
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_t_read() {
    imgOutTmpBlockRam_M_imag_V_t_read = pyrconstuct_top_Loop_3_proc_U0_ap_ready.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_imag_V_t_we0() {
    imgOutTmpBlockRam_M_imag_V_t_we0 = ap_const_logic_0;
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce() {
    imgOutTmpBlockRam_M_real_V_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_i_address0() {
    imgOutTmpBlockRam_M_real_V_i_address0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_address0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_i_ce0() {
    imgOutTmpBlockRam_M_real_V_i_ce0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_ce0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_i_d0() {
    imgOutTmpBlockRam_M_real_V_i_d0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_d0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_i_we0() {
    imgOutTmpBlockRam_M_real_V_i_we0 = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_we0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_i_write() {
    imgOutTmpBlockRam_M_real_V_i_write = ap_chn_write_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_t_address0() {
    imgOutTmpBlockRam_M_real_V_t_address0 = pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_address0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_t_ce0() {
    imgOutTmpBlockRam_M_real_V_t_ce0 = pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_ce0.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_t_d0() {
    imgOutTmpBlockRam_M_real_V_t_d0 = ap_const_lv24_0;
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_t_read() {
    imgOutTmpBlockRam_M_real_V_t_read = pyrconstuct_top_Loop_3_proc_U0_ap_ready.read();
}

void pyrconstuct_top::thread_imgOutTmpBlockRam_M_real_V_t_we0() {
    imgOutTmpBlockRam_M_real_V_t_we0 = ap_const_logic_0;
}

void pyrconstuct_top::thread_imgOutTmpFFTStream_channel_U_ap_dummy_ce() {
    imgOutTmpFFTStream_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void pyrconstuct_top::thread_imgOutTmpFFTStream_channel_din() {
    imgOutTmpFFTStream_channel_din = fft_config1_U0_xk_din.read();
}

void pyrconstuct_top::thread_imgOutTmpFFTStream_channel_read() {
    imgOutTmpFFTStream_channel_read = pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_read.read();
}

void pyrconstuct_top::thread_imgOutTmpFFTStream_channel_write() {
    imgOutTmpFFTStream_channel_write = fft_config1_U0_xk_write.read();
}

void pyrconstuct_top::thread_pyrFilOut_V_TDATA() {
    pyrFilOut_V_TDATA = pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TDATA.read();
}

void pyrconstuct_top::thread_pyrFilOut_V_TVALID() {
    pyrFilOut_V_TVALID = pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TVALID.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue() {
    pyrconstuct_top_Block_codeRepl26_proc_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start() {
    pyrconstuct_top_Block_codeRepl26_proc_U0_ap_start = ap_start.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n() {
    pyrconstuct_top_Block_codeRepl26_proc_U0_fft_config_data_V_full_n = fft_config_data_V_channel_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_proc_U0_ap_continue() {
    pyrconstuct_top_Block_proc_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_proc_U0_ap_start() {
    pyrconstuct_top_Block_proc_U0_ap_start = ap_start.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n() {
    pyrconstuct_top_Block_proc_U0_fft_config2_data_V_full_n = fft_config2_data_V_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_1_proc_U0_ap_continue() {
    pyrconstuct_top_Loop_1_proc_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_1_proc_U0_ap_start() {
    pyrconstuct_top_Loop_1_proc_U0_ap_start = ap_start.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n() {
    pyrconstuct_top_Loop_1_proc_U0_imgInTmp_full_n = imgInTmp_channel_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA() {
    pyrconstuct_top_Loop_1_proc_U0_imgIn_TDATA = imgIn_TDATA.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID() {
    pyrconstuct_top_Loop_1_proc_U0_imgIn_TVALID = imgIn_TVALID.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_2_proc_U0_ap_continue() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_ready_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status.read()))) {
        pyrconstuct_top_Loop_2_proc_U0_ap_continue = ap_const_logic_1;
    } else {
        pyrconstuct_top_Loop_2_proc_U0_ap_continue = ap_const_logic_0;
    }
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status() {
    pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_imag_V_pipo_status = imgOutTmpBlockRam_M_imag_V_i_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status() {
    pyrconstuct_top_Loop_2_proc_U0_imgOutTmpBlockRam_M_real_V_pipo_status = imgOutTmpBlockRam_M_real_V_i_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout() {
    pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_dout = imgOutTmpFFTStream_channel_dout.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n() {
    pyrconstuct_top_Loop_2_proc_U0_imgOutTmpFFTStream_empty_n = imgOutTmpFFTStream_channel_empty_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_ap_continue() {
    pyrconstuct_top_Loop_3_proc_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_ap_start() {
    pyrconstuct_top_Loop_3_proc_U0_ap_start = (imgOutTmpBlockRam_M_real_V_t_empty_n.read() & imgOutTmpBlockRam_M_imag_V_t_empty_n.read());
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n() {
    pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_imag_V_full_n = fftPyrOut_M_imag_V_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n() {
    pyrconstuct_top_Loop_3_proc_U0_fftPyrOut_M_real_V_full_n = fftPyrOut_M_real_V_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0() {
    pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_imag_V_q0 = imgOutTmpBlockRam_M_imag_V_t_q0.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0() {
    pyrconstuct_top_Loop_3_proc_U0_imgOutTmpBlockRam_M_real_V_q0 = imgOutTmpBlockRam_M_real_V_t_q0.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_ap_continue() {
    pyrconstuct_top_Loop_4_proc_U0_ap_continue = ap_const_logic_1;
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout() {
    pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_dout = fftPyrOut_M_imag_V_dout.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n() {
    pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_imag_V_empty_n = fftPyrOut_M_imag_V_empty_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout() {
    pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_dout = fftPyrOut_M_real_V_dout.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n() {
    pyrconstuct_top_Loop_4_proc_U0_fftPyrOut_M_real_V_empty_n = fftPyrOut_M_real_V_empty_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n() {
    pyrconstuct_top_Loop_4_proc_U0_imgInTmp2_full_n = imgInTmp2_channel_full_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_5_proc_U0_ap_continue() {
    pyrconstuct_top_Loop_5_proc_U0_ap_continue = ap_sig_hs_continue.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout() {
    pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_dout = ifftPyrOut_channel_dout.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n() {
    pyrconstuct_top_Loop_5_proc_U0_ifftPyrOut_empty_n = ifftPyrOut_channel_empty_n.read();
}

void pyrconstuct_top::thread_pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY() {
    pyrconstuct_top_Loop_5_proc_U0_pyrFilOut_V_TREADY = pyrFilOut_V_TREADY.read();
}

void pyrconstuct_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imgIn_TDATA\" :  \"" << imgIn_TDATA.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"pyrFilOut_V_TDATA\" :  \"" << pyrFilOut_V_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"nL\" :  \"" << nL.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imgIn_TVALID\" :  \"" << imgIn_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imgIn_TREADY\" :  \"" << imgIn_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pyrFilOut_V_TVALID\" :  \"" << pyrFilOut_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pyrFilOut_V_TREADY\" :  \"" << pyrFilOut_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

